const words = {
            "FET Spelling": {
                "Wk 2": ["beautiful", "calf", "graze", "forest", "angry", "catch", "sad", "promise", "grassy", "happy"],
                "Wk 3": ["agree", "quickly", "return", "surprised", "pleased", "truth", "mad", "protect", "always", "promise"],
                "Wk 4": ["school", "learn", "math", "problem", "important", "think", "art", "because", "creative", "imagination"],
                "Wk 5": ["amazing", "music", "concentrate", "remember", "teamwork", "reason", "best", "learn"],
                "Wk 6": ["baseball", "love", "sport", "college", "team", "allowed", "meet", "field", "cheer", "boo"],
                "Wk 7": ["hard", "season", "become", "nasty", "teammate", "stand", "admire", "die", "baseball", "sport"],
                "Wk 10": ["memory", "discovers", "amaze", "wonder", "tunes", "alone", "struggle", "dream", "achieve", "world"],
                "Wk 11/12": ["wonder", "whisper", "bones", "delight", "children", "mountain", "artist", "surround", "desert", "season"],
                "Wk 13": ["autumn", "spring", "summer", "winter", "speckled", "woven", "showers", "sprout", "bloom", "spread"],
                "Wk 14": ["slither", "barefoot", "flutter", "taste", "scurry", "scatter", "jacket", "secret", "honk", "store"],
                "Wk 15": ["crisp", "gray", "rush", "spider", "weave", "chilly", "zip", "agree", "chipmunk", "dig"],
                "Wk 16": ["autumn", "whisper", "fly", "shake", "spin", "dash", "empty", "jar", "fetch", "lie"]
            },
            "常用單字": {
                "星期": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
                "月份": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
            },
            "CET Vocabulary": {
                "Wk 1&2": ["cool", "fun", "world", "mall", "picnic", "basket", "office", "shop", "fold", "cross"],
                "Wk 3": ["come", "piano", "violin", "music", "building", "cover", "glass", "stair", "shell", "sink"],
                "Wk 4": ["visit", "community", "bookshelf", "library", "real", "front", "garage", "create", "elephant", "climb"],
                "Wk 5": ["country", "hear", "quiet", "mouse", "letter", "cousin", "pick", "excited", "imagine", "phone"],
                "Wk 6": ["feet", "scary", "street", "skateboard", "zoom", "shout", "behind", "jump", "garbage", "can"],
                "Wk 7&8": ["ambulance", "hospital", "city", "busy", "loud", "sick", "tomorrow", "soon", "later"],
                "Wk 10": ["field", "museum", "dinosaur", "drawing", "model", "fossil", "alive", "trip", "break"],
                "Wk 11": ["cow", "together", "puzzle", "about", "could", "show", "chicken", "four", "bird"],
                "Wk 12": ["claw", "catch", "horn", "teeth", "ate", "clue", "flat", "other", "meat", "past"],
                "Wk 13": ["sky", "cloud", "float", "plane", "over", "dream", "stretch", "pilot", "doctor", "silly"],
                "Wk 14": ["train", "neighbor", "ask", "tough", "brave", "remind", "talented", "wait", "minute", "job"],
                "Wk 15&16": ["trick", "fly", "flew", "learn", "start", "famous", "stop"],
                "Wk 18": ["elf", "shoemaker", "imagination", "leather", "shed", "pair", "shiny", "peek"]
            }
        };

        const wordTranslations = {
            "beautiful": "美麗的 (ㄇㄟˇ ㄌㄧˋ ㄉㄜ˙)",
            "calf": "小牛 (ㄒㄧㄠˇ ㄋㄧㄡˊ)",
            "graze": "吃草 (ㄔ ㄘㄠˇ)",
            "forest": "森林 (ㄙㄣ ㄌㄧㄣˊ)",
            "angry": "生氣的 (ㄕㄥ ㄑㄧˋ ㄉㄜ˙)",
            "catch": "抓 (ㄓㄨㄚ)",
            "sad": "難過的 (ㄋㄢˊ ㄍㄨㄛˋ ㄉㄜ˙)",
            "promise": "答應 (ㄉㄚ ㄧㄥˋ)",
            "grassy": "長滿草的 (ㄓㄤˇ ㄇㄢˇ ㄘㄠˇ ㄉㄜ˙)",
            "happy": "快樂的 (ㄎㄨㄞˋ ㄌㄜˋ ㄉㄜ˙)",
            "agree": "同意 (ㄊㄨㄥˊ ㄧˋ)",
            "quickly": "快速地 (ㄎㄨㄞˋ ㄙㄨˋ ㄉㄜ˙)",
            "return": "返回 (ㄈㄢˇ ㄏㄨㄟˊ)",
            "surprised": "驚訝的 (ㄐㄧㄥ ㄧㄚˋ ㄉㄜ˙)",
            "pleased": "高興的 (ㄍㄠ ㄒㄧㄥˋ ㄉㄜ˙)",
            "truth": "真相 (ㄓㄣ ㄒㄧㄤ)",
            "mad": "生氣的 (ㄕㄥ ㄑㄧˋ ㄉㄜ˙)",
            "protect": "保護 (ㄅㄠˇ ㄏㄨˋ)",
            "always": "總是 (ㄗㄨㄥˇ ㄕˋ)",
            "school": "學校 (ㄒㄩㄝˊ ㄒㄧㄠˋ)",
            "learn": "學習 (ㄒㄩㄝˊ ㄒㄧˊ)",
            "math": "數學 (ㄕㄨˋ ㄒㄩㄝˊ)",
            "problem": "問題 (ㄨㄣˋ ㄊㄧˊ)",
            "important": "重要的 (ㄓㄨㄥˋ ㄧㄠˋ ㄉㄜ˙)",
            "think": "思考 (ㄙ ㄎㄠˇ)",
            "art": "藝術 (ㄧˋ ㄕㄨˋ)",
            "because": "因為 (ㄧㄣ ㄨㄟˋ)",
            "creative": "有創意的 (ㄧㄡˇ ㄔㄨㄤˋ ㄧˋ ㄉㄜ˙)",
            "imagination": "想像力 (ㄒㄧㄤˇ ㄒㄧㄤˋ ㄌㄧˋ)",
            "amazing": "驚人的 (ㄐㄧㄥ ㄖㄣˊ ㄉㄜ˙)",
            "music": "音樂 (ㄧㄣ ㄩㄝˋ)",
            "concentrate": "專心 (ㄓㄨㄢ ㄒㄧㄣ)",
            "remember": "記得 (ㄐㄧˋ ㄉㄜˊ)",
            "teamwork": "團隊合作 (ㄊㄨㄢˊ ㄉㄨㄟˋ ㄏㄜˊ ㄗㄨㄛˋ)",
            "reason": "理由 (ㄌㄧˇ ㄧㄡˊ)",
            "best": "最好的 (ㄗㄨㄟˋ ㄏㄠˇ ㄉㄜ˙)",
            "baseball": "棒球 (ㄅㄤˋ ㄑㄧㄡˊ)",
            "love": "愛 (ㄞˋ)",
            "sport": "運動 (ㄩㄣˋ ㄉㄨㄥˋ)",
            "college": "大學 (ㄉㄚˋ ㄒㄩㄝˊ)",
            "team": "隊伍 (ㄉㄨㄟˋ ㄨˇ)",
            "allowed": "允許的 (ㄩㄣˇ ㄒㄩˇ ㄉㄜ˙)",
            "meet": "遇見 (ㄩˋ ㄐㄧㄢˋ)",
            "field": "原野/球場 (ㄩㄢˊ ㄧㄝˇ)",
            "cheer": "歡呼 (ㄏㄨㄢ ㄏㄨ)",
            "boo": "噓聲 (ㄒㄩ ㄕㄥ)",
            "memory": "記憶 (ㄐㄧˋ ㄧˋ)",
            "discovers": "發現 (ㄈㄚ ㄒㄧㄢˋ)",
            "amaze": "使驚訝 (ㄕˇ ㄐㄧㄥ ㄧㄚˋ)",
            "wonder": "奇蹟/想知道 (ㄑㄧˊ ㄐㄧ)",
            "tunes": "曲調 (ㄑㄩˇ ㄉㄧㄠˋ)",
            "alone": "單獨的 (ㄉㄢ ㄉㄨˊ ㄉㄜ˙)",
            "struggle": "掙扎 (ㄓㄥ ㄓㄚˊ)",
            "dream": "夢想 (ㄇㄥˋ ㄒㄧㄤˇ)",
            "achieve": "達成 (ㄉㄚˊ ㄔㄥˊ)",
            "world": "世界 (ㄕˋ ㄐㄧㄝˋ)",
            "whisper": "耳語 (ㄦˇ ㄩˇ)",
            "bones": "骨頭 (ㄍㄨˇ ㄊㄡˊ)",
            "delight": "愉快 (ㄩˊ ㄎㄨㄞˋ)",
            "children": "孩子們 (ㄏㄞˊ ㄗ˙ ㄇㄣ˙)",
            "mountain": "山 (ㄕㄢ)",
            "artist": "藝術家 (ㄧˋ ㄕㄨˋ ㄐㄧㄚ)",
            "surround": "圍繞 (ㄨㄟˊ ㄖㄠˋ)",
            "desert": "沙漠 (ㄕㄚ ㄇㄛˋ)",
            "season": "季節 (ㄐㄧˋ ㄐㄧㄝˊ)",
            "autumn": "秋天 (ㄑㄧㄡ ㄊㄧㄢ)",
            "spring": "春天 (ㄔㄨㄣ ㄊㄧㄢ)",
            "summer": "夏天 (ㄒㄧㄚˋ ㄊㄧㄢ)",
            "winter": "冬天 (ㄉㄨㄥ ㄊㄧㄢ)",
            "speckled": "有斑點的 (ㄧㄡˇ ㄅㄢ ㄉㄧㄢˇ ㄉㄜ˙)",
            "woven": "編織的 (ㄅㄧㄢ ㄓ ㄉㄜ˙)",
            "showers": "陣雨 (ㄓㄣˋ ㄩˇ)",
            "sprout": "發芽 (ㄈㄚ ㄧㄚˊ)",
            "bloom": "開花 (ㄎㄞ ㄏㄨㄚ)",
            "spread": "傳播 (ㄔㄨㄢˊ ㄅㄛˋ)",
            "slither": "滑行 (ㄏㄨㄚˊ ㄒㄧㄥˊ)",
            "barefoot": "赤腳 (ㄔˋ ㄐㄧㄠˇ)",
            "flutter": "拍翅 (ㄆㄞ ㄔˋ)",
            "taste": "味道 (ㄨㄟˋ ㄉㄠˋ)",
            "scurry": "碎步快跑 (ㄙㄨㄟˋ ㄅㄨˋ ㄎㄨㄞˋ ㄆㄠˇ)",
            "scatter": "散開 (ㄙㄢˋ ㄎㄞ)",
            "jacket": "夾克 (ㄐㄧㄚˊ ㄎㄜˋ)",
            "secret": "秘密 (ㄇㄧˋ ㄇㄧˋ)",
            "honk": "喇叭聲 (ㄌㄚˇ ㄅㄚ ㄕㄥ)",
            "store": "商店 (ㄕㄤ ㄉㄧㄢˋ)",
            "crisp": "清爽的 (ㄑㄧㄥ ㄕㄨㄤˇ ㄉㄜ˙)",
            "gray": "灰色的 (ㄏㄨㄟ ㄙㄜˋ ㄉㄜ˙)",
            "rush": "急動 (ㄐㄧˊ ㄉㄨㄥˋ)",
            "spider": "蜘蛛 (ㄓ ㄓㄨ)",
            "weave": "編織 (ㄅㄧㄢ ㄓ)",
            "chilly": "寒冷的 (ㄏㄢˊ ㄌㄥˇ ㄉㄜ˙)",
            "zip": "拉鍊 (ㄌㄚ ㄌㄧㄢˋ)",
            "chipmunk": "花栗鼠 (ㄏㄨㄚ ㄌㄧˋ ㄕㄨˇ)",
            "dig": "挖 (ㄨㄚ)",
            "fly": "飛 (ㄈㄟ)",
            "shake": "搖動 (ㄧㄠˊ ㄉㄨㄥˋ)",
            "spin": "旋轉 (ㄒㄩㄢˊ ㄓㄨㄢˇ)",
            "dash": "衝刺 (ㄔㄨㄥ ㄘˋ)",
            "empty": "空的 (ㄎㄨㄥ ㄉㄜ˙)",
            "jar": "罐子 (ㄍㄨㄢˋ ㄗ˙)",
            "fetch": "拿來 (ㄋㄚˊ ㄌㄞˊ)",
            "lie": "躺/說謊 (ㄊㄤˇ)",
            "hard": "困難的/硬的 (ㄎㄨㄣˋ ㄋㄢˊ ㄉㄜ˙)",
            "become": "變成 (ㄅㄧㄢˋ ㄔㄥˊ)",
            "nasty": "糟糕的 (ㄗㄠ ㄍㄠ ㄉㄜ˙)",
            "teammate": "隊友 (ㄉㄨㄟˋ ㄧㄡˇ)",
            "stand": "站起來 (ㄓㄢˋ ㄑㄧˇ ㄌㄞˊ)",
            "admire": "欣賞/欽佩 (ㄒㄧㄣ ㄕㄤˇ)",
            "die": "死亡 (ㄙˇ ㄨㄤˊ)",
            "cool": "酷的 (ㄎㄨˋ ㄉㄜ˙)",
            "fun": "有趣的 (ㄧㄡˇ ㄑㄩˋ ㄉㄜ˙)",
            "mall": "購物中心 (ㄍㄡˋ ㄨˋ ㄓㄨㄥ ㄒㄧㄣ)",
            "picnic": "野餐 (ㄧㄝˇ ㄘㄢ)",
            "basket": "籃子 (ㄌㄢˊ ㄗ˙)",
            "office": "辦公室 (ㄅㄢˋ ㄍㄨㄥ ㄕˋ)",
            "shop": "商店 (ㄕㄤ ㄉㄧㄢˋ)",
            "fold": "摺疊 (ㄓㄜˊ ㄉㄧㄝˊ)",
            "cross": "越過 (ㄩㄝˋ ㄍㄨㄛˋ)",
            "come": "來 (ㄌㄞˊ)",
            "piano": "鋼琴 (ㄍㄤ ㄑㄧㄣˊ)",
            "violin": "小提琴 (ㄒㄧㄠˇ ㄊㄧˊ ㄑㄧㄣˊ)",
            "building": "建築物 (ㄐㄧㄢˋ ㄓㄨˊ ㄨˋ)",
            "cover": "覆蓋 (ㄈㄨˋ ㄍㄞˋ)",
            "glass": "玻璃 (ㄅㄛ ㄌㄧˊ)",
            "stair": "樓梯 (ㄌㄡˊ ㄊㄧ)",
            "shell": "貝殼 (ㄅㄟˋ ㄎㄜˊ)",
            "sink": "水槽 (ㄕㄨㄟˇ ㄘㄠˊ)",
            "visit": "拜訪 (ㄅㄞˋ ㄈㄤˇ)",
            "community": "社區 (ㄕㄜˋ ㄑㄩ)",
            "bookshelf": "書架 (ㄕㄨ ㄐㄧㄚˋ)",
            "library": "圖書館 (ㄊㄨˊ ㄕㄨ ㄍㄨㄢˇ)",
            "real": "真實的 (ㄓㄣ ㄕˊ ㄉㄜ˙)",
            "front": "前面 (ㄑㄧㄢˊ ㄇㄧㄢˋ)",
            "garage": "車庫 (ㄔㄜ ㄎㄨˋ)",
            "create": "創造 (ㄔㄨㄤˋ ㄗㄠˋ)",
            "elephant": "大象 (ㄉㄚˋ ㄒㄧㄤˋ)",
            "climb": "爬 (ㄆㄚˊ)",
            "country": "國家/鄉村 (ㄒㄧㄤ ㄘㄨㄣ)",
            "hear": "聽見 (ㄊㄧㄥ ㄐㄧㄢˋ)",
            "quiet": "安靜的 (ㄢ ㄐㄧㄥˋ ㄉㄜ˙)",
            "mouse": "老鼠 (ㄌㄠˇ ㄕㄨˇ)",
            "letter": "信/字母 (ㄒㄧㄣˋ)",
            "cousin": "堂表親 (ㄊㄤˊ ㄅㄧㄠˇ ㄑㄧㄣ)",
            "pick": "撿 (ㄐㄧㄢˇ)",
            "excited": "興奮的 (ㄒㄧㄥ ㄈㄣˋ ㄉㄜ˙)",
            "imagine": "想像 (ㄒㄧㄤˇ ㄒㄧㄤˋ)",
            "phone": "電話 (ㄉㄧㄢˋ ㄏㄨㄚˋ)",
            "feet": "腳 (ㄐㄧㄠˇ)",
            "scary": "可怕的 (ㄎㄜˇ ㄆㄚˋ ㄉㄜ˙)",
            "street": "街道 (ㄐㄧㄝ ㄉㄠˋ)",
            "skateboard": "滑板 (ㄏㄨㄚˊ ㄅㄢˇ)",
            "zoom": "快速移動 (ㄎㄨㄞˋ ㄙㄨˋ ㄧˊ ㄉㄨㄥˋ)",
            "shout": "大喊 (ㄉㄚˋ ㄏㄢˇ)",
            "behind": "在...後面 (ㄗㄞˋ...ㄏㄡˋ ㄇㄧㄢˋ)",
            "jump": "跳 (ㄊㄧㄠˋ)",
            "garbage": "垃圾 (ㄌㄜˋ ㄙㄜˋ)",
            "can": "可以/罐子 (ㄎㄜˇ ㄧˇ)",
            "ambulance": "救護車 (ㄐㄧㄡˋ ㄏㄨˋ ㄔㄜ)",
            "hospital": "醫院 (ㄧ ㄩㄢˋ)",
            "city": "城市 (ㄔㄥˊ ㄕˋ)",
            "busy": "忙碌的 (ㄇㄤˊ ㄌㄨˋ ㄉㄜ˙)",
            "loud": "大聲的 (ㄉㄚˋ ㄕㄥ ㄉㄜ˙)",
            "sick": "生病的 (ㄕㄥ ㄅㄧㄥˋ ㄉㄜ˙)",
            "tomorrow": "明天 (ㄇㄧㄥˊ ㄊㄧㄢ)",
            "soon": "很快地 (ㄏㄣˇ ㄎㄨㄞˋ ㄉㄜ˙)",
            "later": "稍後 (ㄕㄠ ㄏㄡˋ)",
            "museum": "博物館 (ㄅㄛˊ ㄨˋ ㄍㄨㄢˇ)",
            "dinosaur": "恐龍 (ㄎㄨㄥˇ ㄌㄨㄥˊ)",
            "drawing": "畫畫 (ㄏㄨㄚˋ ㄏㄨㄚˋ)",
            "model": "模型 (ㄇㄛˊ ㄒㄧㄥˊ)",
            "fossil": "化石 (ㄏㄨㄚˋ ㄕˊ)",
            "alive": "活著的 (ㄏㄨㄛˊ ㄓㄜ˙ ㄉㄜ˙)",
            "trip": "旅行 (ㄌㄩˇ ㄒㄧㄥˊ)",
            "break": "休息 (ㄒㄧㄡ ㄒㄧˊ)",
            "cow": "母牛 (ㄇㄨˇ ㄋㄧㄡˊ)",
            "together": "一起 (ㄧˋ ㄑㄧˇ)",
            "puzzle": "拼圖 (ㄆㄧㄣ ㄊㄨˊ)",
            "about": "關於 (ㄍㄨㄢ ㄩˊ)",
            "could": "可以 (ㄎㄜˇ ㄧˇ)",
            "show": "顯示 (ㄒㄧㄢˇ ㄕˋ)",
            "chicken": "雞 (ㄐㄧ)",
            "four": "四 (ㄙˋ)",
            "bird": "鳥 (ㄋㄧㄠˇ)",
            "claw": "爪子 (ㄓㄨㄚˇ ㄗ˙)",
            "horn": "角 (ㄐㄧㄠˇ)",
            "teeth": "牙齒 (ㄧㄚˊ ㄔˇ)",
            "ate": "吃(過去式) (ㄔ)",
            "clue": "線索 (ㄒㄧㄢˋ ㄙㄨㄛˇ)",
            "flat": "平的 (ㄆㄧㄥˊ ㄉㄜ˙)",
            "other": "其他的 (ㄑㄧˊ ㄊㄚ ㄉㄜ˙)",
            "meat": "肉 (ㄖㄡˋ)",
            "past": "過去 (ㄍㄨㄛˋ ㄑㄩˋ)",
            "sky": "天空 (ㄊㄧㄢ ㄎㄨㄥ)",
            "cloud": "雲 (ㄩㄣˊ)",
            "float": "漂浮 (ㄆㄧㄠ ㄈㄨˊ)",
            "plane": "飛機 (ㄈㄟ ㄐㄧ)",
            "over": "在...上方 (ㄗㄞˋ ... ㄕㄤˋ ㄈㄤ)",
            "stretch": "伸展 (ㄕㄣ ㄓㄢˇ)",
            "pilot": "飛行員 (ㄈㄟ ㄒㄧㄥˊ ㄩㄢˊ)",
            "doctor": "醫生 (ㄧ ㄕㄥ)",
            "silly": "傻的 (ㄕㄚˇ ㄉㄜ˙)",
            "train": "火車 (ㄏㄨㄛˇ ㄔㄜ)",
            "neighbor": "鄰居 (ㄌㄧㄣˊ ㄐㄩ)",
            "ask": "問 (ㄨㄣˋ)",
            "tough": "堅強的 (ㄐㄧㄢ ㄑㄧㄤˊ ㄉㄜ˙)",
            "brave": "勇敢的 (ㄩㄥˇ ㄍㄢˇ ㄉㄜ˙)",
            "remind": "提醒 (ㄊㄧˊ ㄒㄧㄥˇ)",
            "talented": "有天賦的 (ㄧㄡˇ ㄊㄧㄢ ㄈㄨˋ ㄉㄜ˙)",
            "wait": "等待 (ㄉㄥˇ ㄉㄞˋ)",
            "minute": "分鐘 (ㄈㄣ ㄓㄨㄥ)",
            "job": "工作 (ㄍㄨㄥ ㄗㄨㄛˋ)",
            "trick": "把戲 (ㄅㄚˇ ㄒㄧˋ)",
            "flew": "飛(過去式) (ㄈㄟ)",
            "start": "開始 (ㄎㄞ ㄕˇ)",
            "famous": "有名的 (ㄧㄡˇ ㄇㄧㄥˊ ㄉㄜ˙)",
            "stop": "停止 (ㄊㄧㄥˊ ㄓˇ)",
            "elf": "精靈 (ㄐㄧㄥ ㄌㄧㄥˊ)",
            "shoemaker": "鞋匠 (ㄒㄧㄝˊ ㄐㄧㄤˋ)",
            "leather": "皮革 (ㄆㄧˊ ㄍㄜˊ)",
            "shed": "小屋 (ㄒㄧㄠˇ ㄨ)",
            "pair": "一對 (ㄧˊ ㄉㄨㄟˋ)",
            "shiny": "閃亮的 (ㄕㄢˇ ㄌㄧㄤˋ ㄉㄜ˙)",
            "peek": "偷看 (ㄊㄡ ㄎㄢˋ)",
            "Monday": "星期一 (ㄒㄧㄥ ㄑㄧ ㄧ)",
            "Tuesday": "星期二 (ㄒㄧㄥ ㄑㄧ ㄦˋ)",
            "Wednesday": "星期三 (ㄒㄧㄥ ㄑㄧ ㄙㄢ)",
            "Thursday": "星期四 (ㄒㄧㄥ ㄑㄧ ㄙˋ)",
            "Friday": "星期五 (ㄒㄧㄥ ㄑㄧ ㄨˇ)",
            "Saturday": "星期六 (ㄒㄧㄥ ㄑㄧ ㄌㄧㄡˋ)",
            "Sunday": "星期日 (ㄒㄧㄥ ㄑㄧ ㄖˋ)",
            "January": "一月 (ㄧ ㄩㄝˋ)",
            "February": "二月 (ㄦˋ ㄩㄝˋ)",
            "March": "三月 (ㄙㄢ ㄩㄝˋ)",
            "April": "四月 (ㄙˋ ㄩㄝˋ)",
            "May": "五月 (ㄨˇ ㄩㄝˋ)",
            "June": "六月 (ㄌㄧㄡˋ ㄩㄝˋ)",
            "July": "七月 (ㄑㄧ ㄩㄝˋ)",
            "August": "八月 (ㄅㄚ ㄩㄝˋ)",
            "September": "九月 (ㄐㄧㄡˇ ㄩㄝˋ)",
            "October": "十月 (ㄕˊ ㄩㄝˋ)",
            "November": "十一月 (ㄕˊ ㄧ ㄩㄝˋ)",
            "December": "十二月 (ㄕˊ ㄦˋ ㄩㄝˋ)",
        };

        const wordExamples = {
            "beautiful": "The flower is beautiful.", "calf": "The calf follows its mother.", "graze": "Cows graze in the field.", "forest": "Animals live in the forest.", "angry": "He is angry at the dog.", "catch": "She can catch the ball.", "sad": "The boy is sad today.", "promise": "I promise to be kind.", "grassy": "We played on the grassy hill.", "happy": "She is happy to see you.",
            "agree": "I agree with you!", "quickly": "She ran quickly to school.", "return": "He will return home soon.", "surprised": "She was surprised by the gift.", "pleased": "Mom is pleased with the work.", "truth": "Always tell the truth.", "mad": "He felt mad all day.", "protect": "Dogs protect their owners.", "always": "I always brush my teeth.", "school": "She loves going to school.",
            "learn": "We learn new words every day.", "math": "Math class is fun!", "problem": "She solved the hard problem.", "important": "Reading is very important.", "think": "Think before you speak.", "art": "He loves to make art.", "because": "She smiled because she was happy.", "creative": "The child is very creative.", "imagination": "Use your imagination to draw!", "amazing": "The magic show is amazing!",
            "music": "She plays music on the piano.", "concentrate": "Please concentrate on your work.", "remember": "Remember to drink water.", "teamwork": "Good teamwork wins the game.", "reason": "What is the reason you are late?", "best": "She did her best.", "baseball": "He hits the baseball far.", "love": "I love my family.", "sport": "Which sport do you like?", "college": "She studies at college.",
            "team": "Our team won the game!", "allowed": "You are allowed to use a pencil.", "meet": "We meet at the park.", "field": "The cows are in the field.", "cheer": "The crowd will cheer for us.", "boo": "They started to boo the player.", "memory": "She has a great memory.", "discovers": "He discovers a new bug.", "amaze": "The trick will amaze you!", "wonder": "I wonder what is inside.",
            "tunes": "She hummed her favorite tunes.", "alone": "He sat alone under the tree.", "struggle": "She had to struggle to carry the box.", "dream": "I have a big dream!", "achieve": "Work hard to achieve your goal.", "world": "We live in a wonderful world.", "whisper": "She gave a soft whisper.", "bones": "Dogs love to chew on bones.", "delight": "The cake was pure delight.", "children": "The children played in the park.",
            "mountain": "The mountain is very tall.", "artist": "He is a great artist.", "surround": "Trees surround the little house.", "desert": "The desert is hot and dry.", "season": "Which season do you like most?", "autumn": "Leaves fall in autumn.", "spring": "Flowers bloom in spring.", "summer": "We swim in summer.", "winter": "We wear hats in winter.", "speckled": "The egg is speckled with brown dots.",
            "woven": "She wore a woven hat.", "showers": "April showers bring May flowers.", "sprout": "The seeds begin to sprout.", "bloom": "Roses bloom in the garden.", "spread": "The butter spread on the toast.", "slither": "Snakes slither on the ground.", "barefoot": "She ran barefoot on the grass.", "flutter": "Butterflies flutter from flower to flower.", "taste": "This apple has a sweet taste.", "scurry": "Mice scurry across the floor.",
            "scatter": "The wind will scatter the leaves.", "jacket": "Wear a jacket when it is cold.", "secret": "They shared a secret.", "honk": "The car went honk honk!", "store": "Let's go to the store for milk.", "crisp": "The air is crisp in autumn.", "gray": "The sky is gray before it rains.", "rush": "We rush to catch the bus.", "spider": "A spider spun a web.", "weave": "Spiders weave silk webs.",
            "chilly": "The morning is chilly.", "zip": "Zip up your jacket!", "chipmunk": "A chipmunk hid its food.", "dig": "Dogs love to dig holes.", "fly": "Birds can fly very high.", "shake": "Shake the bottle before drinking.", "spin": "The top began to spin.", "dash": "She made a dash for the door.", "empty": "The glass is empty.", "jar": "There is honey in the jar.",
            "fetch": "The dog will fetch the ball.", "lie": "She likes to lie on the grass.", 
            "hard": "The rock is very hard.", "become": "The caterpillar will become a butterfly.", "nasty": "That was a nasty storm.", "teammate": "He is a good teammate.", "stand": "Please stand up when the teacher comes in.", "admire": "I admire your beautiful painting.", "die": "Plants will die without water.",
            "cool": "The breeze feels cool.", "fun": "Swimming is so much fun!", "mall": "We went to the mall on Saturday.", "picnic": "We had a picnic in the park.", "basket": "She put apples in the basket.", "office": "Dad works in an office.", "shop": "Let's shop for shoes today.", "fold": "Please fold the paper in half.",
            "cross": "Look both ways before you cross the street.", "come": "Come and play with me!", "piano": "She plays the piano every day.", "violin": "He plays the violin at school.", "building": "The building is very tall.", "cover": "Cover the pot with a lid.", "glass": "The window is made of glass.", "stair": "Climb the stair to the top.", "shell": "She found a shell at the beach.", "sink": "Wash your hands in the sink.",
            "visit": "We visit grandma on Sunday.", "community": "Everyone helped their community.", "bookshelf": "Fill the bookshelf with books.", "library": "We borrowed books from the library.", "real": "Is that a real butterfly?", "front": "She sat in the front row.", "garage": "Dad parks the car in the garage.", "create": "She used clay to create a pot.", "elephant": "The elephant has a long trunk.", "climb": "He can climb the tall tree.",
            "country": "They live in the country.", "hear": "I can hear the birds sing.", "quiet": "Please be quiet in the library.", "mouse": "The mouse ran under the table.", "letter": "She wrote a letter to her friend.", "cousin": "My cousin lives far away.", "pick": "Pick the ripe apples first.", "excited": "She is so excited to go!", "imagine": "Imagine a land made of candy.", "phone": "Call me on the phone!",
            "feet": "She dipped her feet in the river.", "scary": "The dark cave is scary.", "street": "Our dog walked down the street.", "skateboard": "He loves to ride his skateboard.", "zoom": "The car zoomed past us!", "shout": "Don't shout in the classroom!", "behind": "She hid behind the tree.", "jump": "Jump over the puddle!", "garbage": "Put the garbage in the bin.", "can": "She can swim very well.",
            "ambulance": "The ambulance rushed to the hospital.", "hospital": "The nurse works at the hospital.", "city": "The city has many tall buildings.", "busy": "Mom is very busy today.", "loud": "The music was too loud.", "sick": "He stayed home because he was sick.", "tomorrow": "We will go to the zoo tomorrow.", "soon": "Lunch will be ready soon.", "later": "I will call you later.", "museum": "We saw dinosaur bones at the museum.",
            "dinosaur": "A dinosaur lived long long ago.", "drawing": "She made a lovely drawing.", "model": "He built a model airplane.", "fossil": "They found a fossil in the rock.", "alive": "Plants need water to stay alive.", "trip": "We went on a trip to the beach.", "break": "Let's take a break and drink water.", "cow": "The cow says moo!", "together": "Let's do it together!", "puzzle": "Can you solve the puzzle?",
            "about": "Tell me about your day.", "could": "She could ride a bike.", "show": "Can you show me how to do it?", "chicken": "The chicken laid an egg.", "four": "I have four books.", "bird": "A little bird sat on the branch.", "claw": "The cat stretched out its claw.", "horn": "The rhino has a big horn.", "teeth": "Brush your teeth twice a day.", "ate": "She ate all her vegetables.",
            "clue": "Look for a clue to solve the mystery.", "flat": "The road is flat and smooth.", "other": "Do you have any other ideas?", "meat": "The lion hunts for meat.", "past": "Walk past the red building.", "sky": "The sky is bright blue.", "cloud": "That cloud looks like a fluffy sheep!", "float": "Watch the balloon float away.", "plane": "The plane flew above the clouds.", "over": "She jumped over the puddle.",
            "stretch": "Stretch your arms up high!", "pilot": "The pilot flew the plane.", "doctor": "The doctor helped me feel better.", "silly": "He made a silly face.", "train": "The train went choo choo!", "neighbor": "Our neighbor baked us cookies.", "ask": "Ask your teacher if you need help.", "tough": "It was a tough race but she won!", "brave": "The brave girl spoke in front of the class.", "remind": "Remind me to buy milk.",
            "talented": "She is a very talented singer.", "wait": "Wait for the green light.", "minute": "I will be there in one minute.", "job": "His job is to take care of animals.", "trick": "The magician did a cool trick.", "flew": "The bird flew over the mountain.", "start": "Ready, set, start!", "famous": "She is a famous author.", "stop": "Stop at the red light.", "elf": "An elf helped the shoemaker.",
            "shoemaker": "The shoemaker made shoes all day.", "leather": "The bag is made of leather.", "shed": "Grandpa kept tools in the shed.", "pair": "She bought a new pair of shoes.", "shiny": "The star was shiny and bright.", "peek": "She peeked through the curtain.",
            "Monday": "School starts on Monday.", "Tuesday": "We have P.E. on Tuesday.", "Wednesday": "Wednesday is in the middle of the week.", "Thursday": "I have piano class on Thursday.", "Friday": "Friday is my favorite day!", "Saturday": "We go to the park on Saturday.", "Sunday": "Sunday is a day to rest.",
            "January": "January is the first month.", "February": "Valentine's Day is in February.", "March": "Spring begins in March.", "April": "April showers bring May flowers.", "May": "Mother's Day is in May.", "June": "School ends in June.", "July": "July is very hot!", "August": "We go to the beach in August.", "September": "Leaves fall in September.", "October": "Halloween is in October.", "November": "November is chilly.", "December": "Christmas is in December!"
        };

        const wordImages = {
            "beautiful": "🌸", "calf": "🐄", "graze": "🌾", "forest": "🌳", "angry": "😠", "catch": "⚾", "sad": "😢", "promise": "🤙", "grassy": "🌿", "happy": "😊",
            "agree": "👍", "quickly": "💨", "return": "🔄", "surprised": "😲", "pleased": "😌", "truth": "✅", "mad": "😡", "protect": "🛡️", "always": "♾️", "school": "🏫",
            "learn": "📚", "math": "➕", "problem": "❓", "important": "⭐", "think": "🤔", "art": "🎨", "because": "💬", "creative": "✨", "imagination": "🌈", "amazing": "🤩",
            "music": "🎵", "concentrate": "🧘", "remember": "💡", "teamwork": "🤝", "reason": "🧠", "best": "🥇", "baseball": "⚾", "love": "❤️", "sport": "🏅", "college": "🎓",
            "team": "👥", "allowed": "✅", "meet": "🤝", "field": "🌾", "cheer": "🎉", "boo": "👻", "memory": "🧠", "discovers": "🔍", "amaze": "✨", "wonder": "🌟",
            "tunes": "🎶", "alone": "🧍", "struggle": "💪", "dream": "💭", "achieve": "🏆", "world": "🌍", "whisper": "🤫", "bones": "🦴", "delight": "😄", "children": "👧",
            "mountain": "⛰️", "artist": "🎨", "surround": "🔵", "desert": "🏜️", "season": "🍂", "autumn": "🍁", "spring": "🌸", "summer": "☀️", "winter": "❄️", "speckled": "🥚",
            "woven": "🧺", "showers": "🌧️", "sprout": "🌱", "bloom": "🌺", "spread": "🌊", "slither": "🐍", "barefoot": "🦶", "flutter": "🦋", "taste": "😋", "scurry": "🐭",
            "scatter": "🍃", "jacket": "🧥", "secret": "🤫", "honk": "📯", "store": "🏪", "crisp": "🍏", "gray": "☁️", "rush": "🏃", "spider": "🕷️", "weave": "🕸️",
            "chilly": "🥶", "zip": "🤐", "chipmunk": "🐿️", "dig": "⛏️", "fly": "🦅", "shake": "🫨", "spin": "🌀", "dash": "💨", "empty": "📭", "jar": "🫙",
            "fetch": "🐕", "lie": "🛌", 
            "hard": "🪨", "become": "🦋", "nasty": "🤢", "teammate": "🤝", "stand": "🧍", "admire": "🤩", "die": "🥀",
            "cool": "😎", "fun": "🎠", "mall": "🛒", "picnic": "🧺", "basket": "🛒", "office": "💼", "shop": "🛍️", "fold": "📄",
            "cross": "🚶", "come": "👋", "piano": "🎹", "violin": "🎻", "building": "🏢", "cover": "🍲", "glass": "🪟", "stair": "🪜", "shell": "🐚", "sink": "🚿",
            "visit": "🏡", "community": "🏘️", "bookshelf": "📚", "library": "📖", "real": "👀", "front": "⬆️", "garage": "🚗", "create": "🎨", "elephant": "🐘", "climb": "🧗",
            "country": "🏡", "hear": "👂", "quiet": "🤫", "mouse": "🐭", "letter": "✉️", "cousin": "👨‍👩‍👧", "pick": "🖐️", "excited": "🤩", "imagine": "🌈", "phone": "📱",
            "feet": "🦶", "scary": "👻", "street": "🛣️", "skateboard": "🛹", "zoom": "💨", "shout": "📢", "behind": "🫣", "jump": "🏃", "garbage": "🗑️", "can": "🥫",
            "ambulance": "🚑", "hospital": "🏥", "city": "🌆", "busy": "⏰", "loud": "🔊", "sick": "🤒", "tomorrow": "📅", "soon": "⏳", "later": "🕐", "museum": "🏛️",
            "dinosaur": "🦕", "drawing": "✏️", "model": "✈️", "fossil": "🦴", "alive": "🌱", "trip": "🚌", "break": "☕", "cow": "🐄", "together": "🤝", "puzzle": "🧩",
            "about": "💬", "could": "🙂", "show": "👁️", "chicken": "🐔", "four": "4️⃣", "bird": "🐦", "claw": "🦁", "horn": "🦏", "teeth": "🦷", "ate": "🍽️",
            "clue": "🔍", "flat": "🛣️", "other": "🔁", "meat": "🥩", "past": "⬅️", "sky": "🌤️", "cloud": "☁️", "float": "🎈", "plane": "✈️", "over": "🦅",
            "stretch": "🙆", "pilot": "✈️", "doctor": "👨‍⚕️", "silly": "🤪", "train": "🚂", "neighbor": "🏘️", "ask": "🙋", "tough": "💪", "brave": "🦁", "remind": "🔔",
            "talented": "🎤", "wait": "⏳", "minute": "⏱️", "job": "💼", "trick": "🎩", "flew": "🦅", "start": "🚦", "famous": "⭐", "stop": "🛑", "elf": "🧝",
            "shoemaker": "👞", "leather": "👜", "shed": "🛖", "pair": "👟", "shiny": "✨", "peek": "🙈",
            "Monday": "📅", "Tuesday": "📅", "Wednesday": "📅", "Thursday": "📅", "Friday": "📅", "Saturday": "📅", "Sunday": "📅",
            "January": "❄️", "February": "💝", "March": "🌸", "April": "🌧️", "May": "🌹", "June": "🎓", "July": "☀️", "August": "🏖️", "September": "🍂", "October": "🎃", "November": "🧥", "December": "🎄"
        };