// Daisy 單字資料
//
// curriculum 依「學期」分層。新學期只要在這裡加一組，並把 CURRENT_TERM 指過去，
// 遊戲選單、字典的來源標籤都會自動跟上 —— 不需要改任何頁面。
//
// 為什麼要分學期：一下有 Wk 2，二上也會有 Wk 2。沒有這一層的話，
// words["FET Spelling"]["Wk 2"] 會被後面的直接覆蓋，而且是靜默的。

const CURRENT_TERM = "2-1";

const curriculum = {
  "1-2": {
    label: "一下",
    lists: {
      "FET Spelling": {
        "Wk 2": [
          "beautiful",
          "calf",
          "graze",
          "forest",
          "angry",
          "catch",
          "sad",
          "promise",
          "grassy",
          "happy"
        ],
        "Wk 3": [
          "agree",
          "quickly",
          "return",
          "surprised",
          "pleased",
          "truth",
          "mad",
          "protect",
          "always",
          "promise"
        ],
        "Wk 4": [
          "school",
          "learn",
          "math",
          "problem",
          "important",
          "think",
          "art",
          "because",
          "creative",
          "imagination"
        ],
        "Wk 5": [
          "figure out",
          "amazing",
          "music",
          "concentrate",
          "remember",
          "teamwork",
          "reason",
          "best",
          "important",
          "learn"
        ],
        "Wk 6": [
          "baseball",
          "love",
          "sport",
          "college",
          "team",
          "allowed",
          "meet",
          "field",
          "cheer",
          "boo"
        ],
        "Wk 7": [
          "hard",
          "season",
          "become",
          "nasty",
          "teammate",
          "stand up",
          "admire",
          "die",
          "baseball",
          "sport"
        ],
        "Wk 10": [
          "memory",
          "discovers",
          "amaze",
          "wonder",
          "tunes",
          "alone",
          "struggle",
          "dream",
          "achieve",
          "world"
        ],
        "Wk 11/12": [
          "wonder",
          "whisper",
          "bones",
          "delight",
          "children",
          "mountain",
          "artist",
          "surround",
          "desert",
          "season"
        ],
        "Wk 13": [
          "autumn",
          "spring",
          "summer",
          "winter",
          "speckled",
          "woven",
          "showers",
          "sprout",
          "bloom",
          "spread"
        ],
        "Wk 14": [
          "slither",
          "barefoot",
          "flutter",
          "taste",
          "scurry",
          "scatter",
          "jacket",
          "secret",
          "honk",
          "store"
        ],
        "Wk 15": [
          "crisp",
          "gray",
          "rush",
          "spider",
          "weave",
          "chilly",
          "zip",
          "agree",
          "chipmunk",
          "dig"
        ],
        "Wk 16": [
          "autumn",
          "whisper",
          "fly",
          "shake",
          "spin",
          "dash",
          "empty",
          "jar",
          "fetch",
          "lie"
        ]
      },
      "CET Vocabulary": {
        "Wk 1&2": [
          "cool",
          "fun",
          "world",
          "mall",
          "picnic",
          "basket",
          "office",
          "shop",
          "fold",
          "cross"
        ],
        "Wk 3": [
          "come",
          "piano",
          "violin",
          "music",
          "building",
          "cover",
          "glass",
          "stair",
          "shell",
          "sink"
        ],
        "Wk 4": [
          "visit",
          "community",
          "bookshelf",
          "library",
          "real",
          "front",
          "garage",
          "create",
          "elephant",
          "climb"
        ],
        "Wk 5": [
          "country",
          "hear",
          "quiet",
          "mouse",
          "letter",
          "cousin",
          "pick",
          "excited",
          "imagine",
          "phone"
        ],
        "Wk 6": [
          "feet",
          "scary",
          "street",
          "skateboard",
          "zoom",
          "shout",
          "behind",
          "jump",
          "garbage",
          "can"
        ],
        "Wk 7&8": [
          "ambulance",
          "hospital",
          "city",
          "busy",
          "loud",
          "sick",
          "tomorrow",
          "soon",
          "later"
        ],
        "Wk 10": [
          "field",
          "museum",
          "dinosaur",
          "drawing",
          "model",
          "fossil",
          "alive",
          "trip",
          "break"
        ],
        "Wk 11": [
          "cow",
          "together",
          "puzzle",
          "about",
          "could",
          "show",
          "chicken",
          "four",
          "bird"
        ],
        "Wk 12": [
          "claw",
          "catch",
          "horn",
          "teeth",
          "ate",
          "clue",
          "flat",
          "other",
          "meat",
          "past"
        ],
        "Wk 13": [
          "sky",
          "cloud",
          "float",
          "plane",
          "over",
          "dream",
          "stretch",
          "pilot",
          "doctor",
          "silly"
        ],
        "Wk 14": [
          "train",
          "neighbor",
          "ask",
          "tough",
          "brave",
          "remind",
          "talented",
          "wait",
          "minute",
          "job"
        ],
        "Wk 15&16": [
          "trick",
          "fly",
          "flew",
          "learn",
          "start",
          "famous",
          "stop"
        ],
        "Wk 18": [
          "elf",
          "shoemaker",
          "imagination",
          "leather",
          "shed",
          "pair",
          "shiny",
          "peek"
        ]
      }
    }
  },

  "2-1": {
    label: "二上",
    lists: {
      "FET Spelling": {
        "Wk 1": [
          "shadow",
          "meeting",
          "scurry",
          "flutter",
          "nod",
          "colorful",
          "plant",
          "garden",
          "landlord",
          "window box"
        ],
        "Wk 2": [
          "soil",
          "elevator",
          "important",
          "pour",
          "hang",
          "invite",
          "bloom",
          "scent",
          "joy",
          "admire"
        ],
        "Wk 3": [
          "backyard",
          "daylight",
          "seaweed",
          "snapshot",
          "bright",
          "gasp",
          "wink",
          "arrive",
          "seagull",
          "steep"
        ],
        "Wk 4": [
          "notice",
          "explain",
          "shallow",
          "critter",
          "collect",
          "cell phone",
          "creature",
          "hermit crab",
          "explore",
          "pleasure"
        ],
        "Wk 5": [
          "excited",
          "favorite",
          "tour",
          "guide",
          "explore",
          "different",
          "strange",
          "empty",
          "cactus",
          "climb"
        ],
        "Wk 6": [
          "desert",
          "vulture",
          "glass",
          "lizard",
          "crawl",
          "match",
          "fun fact",
          "lead",
          "assistant",
          "decide"
        ],
        "Wk 7": [
          "meeting",
          "plant",
          "hang",
          "scent",
          "snapshot",
          "daylight",
          "collect",
          "pleasure",
          "strange",
          "match"
        ],
        "Wk 10": [
          "grassy",
          "prairie dog",
          "owl",
          "coyote",
          "pattern",
          "map",
          "alike",
          "Africa",
          "Asia",
          "Europe"
        ],
        "Wk 11": [
          "prairie",
          "habitat",
          "grazer",
          "burrow",
          "colony",
          "imagine",
          "grassland",
          "bison",
          "hole",
          "badger"
        ],
        "Wk 12": [
          "underground",
          "peek",
          "hide",
          "enemy",
          "rattle",
          "hawk",
          "ferret",
          "exciting",
          "connect",
          "deer"
        ],
        "Wk 13": [
          "slowly",
          "carefully",
          "quietly",
          "glow",
          "rustle",
          "decorate",
          "shade",
          "swing",
          "pick",
          "tree house"
        ],
        "Wk 14": [
          "shake",
          "shelter",
          "fort",
          "company",
          "melt",
          "honey",
          "armful",
          "shower",
          "gather",
          "branch"
        ],
        "Wk 15": [
          "oval",
          "waddle",
          "huddle",
          "flock",
          "stare",
          "frown",
          "tuck",
          "slide",
          "wander",
          "alone"
        ],
        "Wk 16": [
          "cheerful",
          "forget",
          "storm",
          "race",
          "shield",
          "glad",
          "broken",
          "gasp",
          "chick",
          "sigh"
        ],
        "Wk 17": [
          "habitat",
          "imagine",
          "peek",
          "exciting",
          "decorate",
          "quietly",
          "armful",
          "company",
          "alone",
          "storm"
        ]
      },
      "CET Vocabulary": {
        "Wk 1&2": [
          "visit",
          "huge",
          "reply",
          "holiday",
          "souvenir",
          "booth",
          "rush",
          "outside",
          "upset",
          "thought"
        ],
        "Wk 3": [
          "hang",
          "know",
          "believe",
          "only",
          "suspect",
          "lead",
          "shocked",
          "disappear",
          "symbol",
          "cover"
        ],
        "Wk 4": [
          "notice",
          "busy",
          "flour",
          "worried",
          "forgive",
          "solve",
          "nod",
          "stealing",
          "month",
          "fair"
        ],
        "Wk 5": [
          "planet",
          "surface",
          "space",
          "divide",
          "piece",
          "continent",
          "natural",
          "feature",
          "landform",
          "valley"
        ],
        "Wk 6": [
          "lie",
          "wide",
          "island",
          "flow",
          "popular",
          "survive",
          "salty",
          "human",
          "produce",
          "breathe"
        ],
        "Wk 7": [
          "bottom",
          "strong",
          "wave",
          "hurricane",
          "cause",
          "storm",
          "grow",
          "damage",
          "freeze",
          "thick"
        ],
        "Wk 10": [
          "dance",
          "activity",
          "culture",
          "begin",
          "country",
          "tour",
          "traditional",
          "native",
          "honor",
          "thanks"
        ],
        "Wk 11": [
          "perform",
          "metal",
          "cone",
          "noise",
          "gathering",
          "American",
          "competition",
          "across",
          "fancy",
          "movement"
        ],
        "Wk 12": [
          "smooth",
          "chant",
          "drum",
          "necklace",
          "history",
          "legend",
          "alive",
          "hula-hoop",
          "name after",
          "stomp"
        ],
        "Wk 13": [
          "heel",
          "rhythm",
          "fiddle",
          "leather",
          "train",
          "famous",
          "company",
          "be known for",
          "make sense",
          "present"
        ],
        "Wk 14": [
          "sugar",
          "cereal",
          "allow",
          "adult",
          "entire",
          "cottage",
          "general",
          "wonderful",
          "beg",
          "lesson"
        ],
        "Wk 15": [
          "excited",
          "in case",
          "nervously",
          "ready",
          "exclaim",
          "slip into",
          "gasp",
          "scared",
          "decision",
          "deep"
        ],
        "Wk 16&17": [
          "hard",
          "almost",
          "worry",
          "stretch",
          "cheer",
          "wave",
          "proud",
          "even though",
          "forget",
          "sunscreen"
        ],
        "Wk 20": [
          "discover",
          "spine",
          "predator",
          "nutrient",
          "mammal",
          "blind",
          "sense",
          "attract",
          "protect",
          "endangered"
        ]
      }
    }
  }
  // 二下： "2-2": { label: "二下", lists: { "FET Spelling": {...}, ... } }
};

// 不屬於任何學期、一直都用得到的字
const evergreen = {
  "常用單字": {
    "星期": [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday"
    ],
    "月份": [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
    ]
  }
};

const wordEntries = {
  "figure out": { s:[{zh:"想出",z:["ㄒㄧㄤˇ","ㄔㄨ"]}] },
  "stand up": { s:[{zh:"站起來",z:["ㄓㄢˋ","ㄑㄧˇ","ㄌㄞ˙"]}] },
  "beautiful": { s:[{zh:"美麗的",z:["ㄇㄟˇ","ㄌㄧˋ","ㄉㄜ˙"]}] },
  "calf": { s:[{zh:"小牛",z:["ㄒㄧㄠˇ","ㄋㄧㄡˊ"]}] },
  "graze": { s:[{zh:"吃草",z:["ㄔ","ㄘㄠˇ"]}] },
  "forest": { s:[{zh:"森林",z:["ㄙㄣ","ㄌㄧㄣˊ"]}] },
  "angry": { s:[{zh:"生氣的",z:["ㄕㄥ","ㄑㄧˋ","ㄉㄜ˙"]}] },
  "catch": { s:[{zh:"抓",z:["ㄓㄨㄚ"]}] },
  "sad": { s:[{zh:"難過的",z:["ㄋㄢˊ","ㄍㄨㄛˋ","ㄉㄜ˙"]}] },
  "promise": { s:[{zh:"答應",z:["ㄉㄚ","ㄧㄥˋ"]}] },
  "grassy": { s:[{zh:"長滿草的",z:["ㄓㄤˇ","ㄇㄢˇ","ㄘㄠˇ","ㄉㄜ˙"]}] },
  "happy": { s:[{zh:"快樂的",z:["ㄎㄨㄞˋ","ㄌㄜˋ","ㄉㄜ˙"]}] },
  "agree": { s:[{zh:"同意",z:["ㄊㄨㄥˊ","ㄧˋ"]}] },
  "quickly": { s:[{zh:"快速地",z:["ㄎㄨㄞˋ","ㄙㄨˋ","ㄉㄜ˙"]}] },
  "return": { s:[{zh:"返回",z:["ㄈㄢˇ","ㄏㄨㄟˊ"]}] },
  "surprised": { s:[{zh:"驚訝的",z:["ㄐㄧㄥ","ㄧㄚˋ","ㄉㄜ˙"]}] },
  "pleased": { s:[{zh:"高興的",z:["ㄍㄠ","ㄒㄧㄥˋ","ㄉㄜ˙"]}] },
  "truth": { s:[{zh:"真相",z:["ㄓㄣ","ㄒㄧㄤˋ"]}] },
  "mad": { s:[{zh:"生氣的",z:["ㄕㄥ","ㄑㄧˋ","ㄉㄜ˙"]}] },
  "protect": { s:[{zh:"保護",z:["ㄅㄠˇ","ㄏㄨˋ"]}] },
  "always": { s:[{zh:"總是",z:["ㄗㄨㄥˇ","ㄕˋ"]}] },
  "school": { s:[{zh:"學校",z:["ㄒㄩㄝˊ","ㄒㄧㄠˋ"]}] },
  "learn": { s:[{zh:"學習",z:["ㄒㄩㄝˊ","ㄒㄧˊ"]}] },
  "math": { s:[{zh:"數學",z:["ㄕㄨˋ","ㄒㄩㄝˊ"]}] },
  "problem": { s:[{zh:"問題",z:["ㄨㄣˋ","ㄊㄧˊ"]}] },
  "important": { s:[{zh:"重要的",z:["ㄓㄨㄥˋ","ㄧㄠˋ","ㄉㄜ˙"]}] },
  "think": { s:[{zh:"思考",z:["ㄙ","ㄎㄠˇ"]}] },
  "art": { s:[{zh:"藝術",z:["ㄧˋ","ㄕㄨˋ"]}] },
  "because": { s:[{zh:"因為",z:["ㄧㄣ","ㄨㄟˋ"]}] },
  "creative": { s:[{zh:"有創意的",z:["ㄧㄡˇ","ㄔㄨㄤˋ","ㄧˋ","ㄉㄜ˙"]}] },
  "imagination": { s:[{zh:"想像力",z:["ㄒㄧㄤˇ","ㄒㄧㄤˋ","ㄌㄧˋ"]}] },
  "amazing": { s:[{zh:"驚人的",z:["ㄐㄧㄥ","ㄖㄣˊ","ㄉㄜ˙"]}] },
  "music": { s:[{zh:"音樂",z:["ㄧㄣ","ㄩㄝˋ"]}] },
  "concentrate": { s:[{zh:"專心",z:["ㄓㄨㄢ","ㄒㄧㄣ"]}] },
  "remember": { s:[{zh:"記得",z:["ㄐㄧˋ","ㄉㄜˊ"]}] },
  "teamwork": { s:[{zh:"團隊合作",z:["ㄊㄨㄢˊ","ㄉㄨㄟˋ","ㄏㄜˊ","ㄗㄨㄛˋ"]}] },
  "reason": { s:[{zh:"理由",z:["ㄌㄧˇ","ㄧㄡˊ"]}] },
  "best": { s:[{zh:"最好的",z:["ㄗㄨㄟˋ","ㄏㄠˇ","ㄉㄜ˙"]}] },
  "baseball": { s:[{zh:"棒球",z:["ㄅㄤˋ","ㄑㄧㄡˊ"]}] },
  "love": { s:[{zh:"愛",z:["ㄞˋ"]}] },
  "sport": { s:[{zh:"運動",z:["ㄩㄣˋ","ㄉㄨㄥˋ"]}] },
  "college": { s:[{zh:"大學",z:["ㄉㄚˋ","ㄒㄩㄝˊ"]}] },
  "team": { s:[{zh:"隊伍",z:["ㄉㄨㄟˋ","ㄨˇ"]}] },
  "allowed": { s:[{zh:"允許的",z:["ㄩㄣˇ","ㄒㄩˇ","ㄉㄜ˙"]}] },
  "meet": { s:[{zh:"遇見",z:["ㄩˋ","ㄐㄧㄢˋ"]}] },
  "field": { s:[{zh:"原野",z:["ㄩㄢˊ","ㄧㄝˇ"]},{zh:"球場",z:["ㄑㄧㄡˊ","ㄔㄤˇ"]}] },
  "cheer": { s:[{zh:"歡呼",z:["ㄏㄨㄢ","ㄏㄨ"]}] },
  "boo": { s:[{zh:"噓聲",z:["ㄒㄩ","ㄕㄥ"]}] },
  "memory": { s:[{zh:"記憶",z:["ㄐㄧˋ","ㄧˋ"]}] },
  "discovers": { s:[{zh:"發現",z:["ㄈㄚ","ㄒㄧㄢˋ"]}] },
  "amaze": { s:[{zh:"使驚訝",z:["ㄕˇ","ㄐㄧㄥ","ㄧㄚˋ"]}] },
  "wonder": { s:[{zh:"奇蹟",z:["ㄑㄧˊ","ㄐㄧ"]},{zh:"想知道",z:["ㄒㄧㄤˇ","ㄓ","ㄉㄠˋ"]}] },
  "tunes": { s:[{zh:"曲調",z:["ㄑㄩˇ","ㄉㄧㄠˋ"]}] },
  "alone": { s:[{zh:"單獨的",z:["ㄉㄢ","ㄉㄨˊ","ㄉㄜ˙"]}] },
  "struggle": { s:[{zh:"掙扎",z:["ㄓㄥ","ㄓㄚˊ"]}] },
  "dream": { s:[{zh:"夢想",z:["ㄇㄥˋ","ㄒㄧㄤˇ"]}] },
  "achieve": { s:[{zh:"達成",z:["ㄉㄚˊ","ㄔㄥˊ"]}] },
  "world": { s:[{zh:"世界",z:["ㄕˋ","ㄐㄧㄝˋ"]}] },
  "whisper": { s:[{zh:"耳語",z:["ㄦˇ","ㄩˇ"]}] },
  "bones": { s:[{zh:"骨頭",z:["ㄍㄨˇ","ㄊㄡ˙"]}] },
  "delight": { s:[{zh:"愉快",z:["ㄩˊ","ㄎㄨㄞˋ"]}] },
  "children": { s:[{zh:"孩子們",z:["ㄏㄞˊ","ㄗ˙","ㄇㄣ˙"]}] },
  "mountain": { s:[{zh:"山",z:["ㄕㄢ"]}] },
  "artist": { s:[{zh:"藝術家",z:["ㄧˋ","ㄕㄨˋ","ㄐㄧㄚ"]}] },
  "surround": { s:[{zh:"圍繞",z:["ㄨㄟˊ","ㄖㄠˋ"]}] },
  "desert": { s:[{zh:"沙漠",z:["ㄕㄚ","ㄇㄛˋ"]}] },
  "season": { s:[{zh:"季節",z:["ㄐㄧˋ","ㄐㄧㄝˊ"]}] },
  "autumn": { s:[{zh:"秋天",z:["ㄑㄧㄡ","ㄊㄧㄢ"]}] },
  "spring": { s:[{zh:"春天",z:["ㄔㄨㄣ","ㄊㄧㄢ"]}] },
  "summer": { s:[{zh:"夏天",z:["ㄒㄧㄚˋ","ㄊㄧㄢ"]}] },
  "winter": { s:[{zh:"冬天",z:["ㄉㄨㄥ","ㄊㄧㄢ"]}] },
  "speckled": { s:[{zh:"有斑點的",z:["ㄧㄡˇ","ㄅㄢ","ㄉㄧㄢˇ","ㄉㄜ˙"]}] },
  "woven": { s:[{zh:"編織的",z:["ㄅㄧㄢ","ㄓ","ㄉㄜ˙"]}] },
  "showers": { s:[{zh:"陣雨",z:["ㄓㄣˋ","ㄩˇ"]}] },
  "sprout": { s:[{zh:"發芽",z:["ㄈㄚ","ㄧㄚˊ"]}] },
  "bloom": { s:[{zh:"開花",z:["ㄎㄞ","ㄏㄨㄚ"]}] },
  "spread": { s:[{zh:"傳播",z:["ㄔㄨㄢˊ","ㄅㄛˋ"]}] },
  "slither": { s:[{zh:"滑行",z:["ㄏㄨㄚˊ","ㄒㄧㄥˊ"]}] },
  "barefoot": { s:[{zh:"赤腳",z:["ㄔˋ","ㄐㄧㄠˇ"]}] },
  "flutter": { s:[{zh:"拍翅",z:["ㄆㄞ","ㄔˋ"]}] },
  "taste": { s:[{zh:"味道",z:["ㄨㄟˋ","ㄉㄠˋ"]}] },
  "scurry": { s:[{zh:"碎步快跑",z:["ㄙㄨㄟˋ","ㄅㄨˋ","ㄎㄨㄞˋ","ㄆㄠˇ"]}] },
  "scatter": { s:[{zh:"散開",z:["ㄙㄢˋ","ㄎㄞ"]}] },
  "jacket": { s:[{zh:"夾克",z:["ㄐㄧㄚˊ","ㄎㄜˋ"]}] },
  "secret": { s:[{zh:"秘密",z:["ㄇㄧˋ","ㄇㄧˋ"]}] },
  "honk": { s:[{zh:"喇叭聲",z:["ㄌㄚˇ","ㄅㄚ","ㄕㄥ"]}] },
  "store": { s:[{zh:"商店",z:["ㄕㄤ","ㄉㄧㄢˋ"]}] },
  "crisp": { s:[{zh:"清爽的",z:["ㄑㄧㄥ","ㄕㄨㄤˇ","ㄉㄜ˙"]}] },
  "gray": { s:[{zh:"灰色的",z:["ㄏㄨㄟ","ㄙㄜˋ","ㄉㄜ˙"]}] },
  "rush": { s:[{zh:"急動",z:["ㄐㄧˊ","ㄉㄨㄥˋ"]}] },
  "spider": { s:[{zh:"蜘蛛",z:["ㄓ","ㄓㄨ"]}] },
  "weave": { s:[{zh:"編織",z:["ㄅㄧㄢ","ㄓ"]}] },
  "chilly": { s:[{zh:"寒冷的",z:["ㄏㄢˊ","ㄌㄥˇ","ㄉㄜ˙"]}] },
  "zip": { s:[{zh:"拉鍊",z:["ㄌㄚ","ㄌㄧㄢˋ"]}] },
  "chipmunk": { s:[{zh:"花栗鼠",z:["ㄏㄨㄚ","ㄌㄧˋ","ㄕㄨˇ"]}] },
  "dig": { s:[{zh:"挖",z:["ㄨㄚ"]}] },
  "fly": { s:[{zh:"飛",z:["ㄈㄟ"]}] },
  "shake": { s:[{zh:"搖動",z:["ㄧㄠˊ","ㄉㄨㄥˋ"]}] },
  "spin": { s:[{zh:"旋轉",z:["ㄒㄩㄢˊ","ㄓㄨㄢˇ"]}] },
  "dash": { s:[{zh:"衝刺",z:["ㄔㄨㄥ","ㄘˋ"]}] },
  "empty": { s:[{zh:"空的",z:["ㄎㄨㄥ","ㄉㄜ˙"]}] },
  "jar": { s:[{zh:"罐子",z:["ㄍㄨㄢˋ","ㄗ˙"]}] },
  "fetch": { s:[{zh:"拿來",z:["ㄋㄚˊ","ㄌㄞˊ"]}] },
  "lie": { s:[{zh:"躺",z:["ㄊㄤˇ"]},{zh:"說謊",z:["ㄕㄨㄛ","ㄏㄨㄤˇ"]},{zh:"位於",z:["ㄨㄟˋ","ㄩˊ"]}] },
  "hard": { s:[{zh:"困難的",z:["ㄎㄨㄣˋ","ㄋㄢˊ","ㄉㄜ˙"]},{zh:"硬的",z:["ㄧㄥˋ","ㄉㄜ˙"]},{zh:"努力地",z:["ㄋㄨˇ","ㄌㄧˋ","ㄉㄜ˙"]}] },
  "become": { s:[{zh:"變成",z:["ㄅㄧㄢˋ","ㄔㄥˊ"]}] },
  "nasty": { s:[{zh:"糟糕的",z:["ㄗㄠ","ㄍㄠ","ㄉㄜ˙"]}] },
  "teammate": { s:[{zh:"隊友",z:["ㄉㄨㄟˋ","ㄧㄡˇ"]}] },
  "stand": { s:[{zh:"站起來",z:["ㄓㄢˋ","ㄑㄧˇ","ㄌㄞˊ"]}] },
  "admire": { s:[{zh:"欣賞",z:["ㄒㄧㄣ","ㄕㄤˇ"]},{zh:"欽佩",z:["ㄑㄧㄣ","ㄆㄟˋ"]}] },
  "die": { s:[{zh:"死亡",z:["ㄙˇ","ㄨㄤˊ"]}] },
  "cool": { s:[{zh:"酷的",z:["ㄎㄨˋ","ㄉㄜ˙"]}] },
  "fun": { s:[{zh:"有趣的",z:["ㄧㄡˇ","ㄑㄩˋ","ㄉㄜ˙"]}] },
  "mall": { s:[{zh:"購物中心",z:["ㄍㄡˋ","ㄨˋ","ㄓㄨㄥ","ㄒㄧㄣ"]}] },
  "picnic": { s:[{zh:"野餐",z:["ㄧㄝˇ","ㄘㄢ"]}] },
  "basket": { s:[{zh:"籃子",z:["ㄌㄢˊ","ㄗ˙"]}] },
  "office": { s:[{zh:"辦公室",z:["ㄅㄢˋ","ㄍㄨㄥ","ㄕˋ"]}] },
  "shop": { s:[{zh:"商店",z:["ㄕㄤ","ㄉㄧㄢˋ"]}] },
  "fold": { s:[{zh:"摺疊",z:["ㄓㄜˊ","ㄉㄧㄝˊ"]}] },
  "cross": { s:[{zh:"越過",z:["ㄩㄝˋ","ㄍㄨㄛˋ"]}] },
  "come": { s:[{zh:"來",z:["ㄌㄞˊ"]}] },
  "piano": { s:[{zh:"鋼琴",z:["ㄍㄤ","ㄑㄧㄣˊ"]}] },
  "violin": { s:[{zh:"小提琴",z:["ㄒㄧㄠˇ","ㄊㄧˊ","ㄑㄧㄣˊ"]}] },
  "building": { s:[{zh:"建築物",z:["ㄐㄧㄢˋ","ㄓㄨˊ","ㄨˋ"]}] },
  "cover": { s:[{zh:"覆蓋",z:["ㄈㄨˋ","ㄍㄞˋ"]}] },
  "glass": { s:[{zh:"玻璃",z:["ㄅㄛ","ㄌㄧˊ"]}] },
  "stair": { s:[{zh:"樓梯",z:["ㄌㄡˊ","ㄊㄧ"]}] },
  "shell": { s:[{zh:"貝殼",z:["ㄅㄟˋ","ㄎㄜˊ"]}] },
  "sink": { s:[{zh:"水槽",z:["ㄕㄨㄟˇ","ㄘㄠˊ"]}] },
  "visit": { s:[{zh:"拜訪",z:["ㄅㄞˋ","ㄈㄤˇ"]}] },
  "community": { s:[{zh:"社區",z:["ㄕㄜˋ","ㄑㄩ"]}] },
  "bookshelf": { s:[{zh:"書架",z:["ㄕㄨ","ㄐㄧㄚˋ"]}] },
  "library": { s:[{zh:"圖書館",z:["ㄊㄨˊ","ㄕㄨ","ㄍㄨㄢˇ"]}] },
  "real": { s:[{zh:"真實的",z:["ㄓㄣ","ㄕˊ","ㄉㄜ˙"]}] },
  "front": { s:[{zh:"前面",z:["ㄑㄧㄢˊ","ㄇㄧㄢˋ"]}] },
  "garage": { s:[{zh:"車庫",z:["ㄔㄜ","ㄎㄨˋ"]}] },
  "create": { s:[{zh:"創造",z:["ㄔㄨㄤˋ","ㄗㄠˋ"]}] },
  "elephant": { s:[{zh:"大象",z:["ㄉㄚˋ","ㄒㄧㄤˋ"]}] },
  "climb": { s:[{zh:"爬",z:["ㄆㄚˊ"]}] },
  "country": { s:[{zh:"國家",z:["ㄍㄨㄛˊ","ㄐㄧㄚ"]},{zh:"鄉村",z:["ㄒㄧㄤ","ㄘㄨㄣ"]}] },
  "hear": { s:[{zh:"聽見",z:["ㄊㄧㄥ","ㄐㄧㄢˋ"]}] },
  "quiet": { s:[{zh:"安靜的",z:["ㄢ","ㄐㄧㄥˋ","ㄉㄜ˙"]}] },
  "mouse": { s:[{zh:"老鼠",z:["ㄌㄠˇ","ㄕㄨˇ"]}] },
  "letter": { s:[{zh:"信",z:["ㄒㄧㄣˋ"]},{zh:"字母",z:["ㄗˋ","ㄇㄨˇ"]}] },
  "cousin": { s:[{zh:"堂表親",z:["ㄊㄤˊ","ㄅㄧㄠˇ","ㄑㄧㄣ"]}] },
  "pick": { s:[{zh:"撿",z:["ㄐㄧㄢˇ"]},{zh:"摘",z:["ㄓㄞ"]}] },
  "excited": { s:[{zh:"興奮的",z:["ㄒㄧㄥ","ㄈㄣˋ","ㄉㄜ˙"]}] },
  "imagine": { s:[{zh:"想像",z:["ㄒㄧㄤˇ","ㄒㄧㄤˋ"]}] },
  "phone": { s:[{zh:"電話",z:["ㄉㄧㄢˋ","ㄏㄨㄚˋ"]}] },
  "feet": { s:[{zh:"腳",z:["ㄐㄧㄠˇ"]}] },
  "scary": { s:[{zh:"可怕的",z:["ㄎㄜˇ","ㄆㄚˋ","ㄉㄜ˙"]}] },
  "street": { s:[{zh:"街道",z:["ㄐㄧㄝ","ㄉㄠˋ"]}] },
  "skateboard": { s:[{zh:"滑板",z:["ㄏㄨㄚˊ","ㄅㄢˇ"]}] },
  "zoom": { s:[{zh:"快速移動",z:["ㄎㄨㄞˋ","ㄙㄨˋ","ㄧˊ","ㄉㄨㄥˋ"]}] },
  "shout": { s:[{zh:"大喊",z:["ㄉㄚˋ","ㄏㄢˇ"]}] },
  "behind": { s:[{zh:"在……後面",z:["ㄗㄞˋ","","","ㄏㄡˋ","ㄇㄧㄢ˙"]}] },
  "jump": { s:[{zh:"跳",z:["ㄊㄧㄠˋ"]}] },
  "garbage": { s:[{zh:"垃圾",z:["ㄌㄜˋ","ㄙㄜˋ"]}] },
  "can": { s:[{zh:"可以",z:["ㄎㄜˇ","ㄧˇ"]},{zh:"罐子",z:["ㄍㄨㄢˋ","ㄗ˙"]}] },
  "ambulance": { s:[{zh:"救護車",z:["ㄐㄧㄡˋ","ㄏㄨˋ","ㄔㄜ"]}] },
  "hospital": { s:[{zh:"醫院",z:["ㄧ","ㄩㄢˋ"]}] },
  "city": { s:[{zh:"城市",z:["ㄔㄥˊ","ㄕˋ"]}] },
  "busy": { s:[{zh:"忙碌的",z:["ㄇㄤˊ","ㄌㄨˋ","ㄉㄜ˙"]}] },
  "loud": { s:[{zh:"大聲的",z:["ㄉㄚˋ","ㄕㄥ","ㄉㄜ˙"]}] },
  "sick": { s:[{zh:"生病的",z:["ㄕㄥ","ㄅㄧㄥˋ","ㄉㄜ˙"]}] },
  "tomorrow": { s:[{zh:"明天",z:["ㄇㄧㄥˊ","ㄊㄧㄢ"]}] },
  "soon": { s:[{zh:"很快地",z:["ㄏㄣˇ","ㄎㄨㄞˋ","ㄉㄜ˙"]}] },
  "later": { s:[{zh:"稍後",z:["ㄕㄠ","ㄏㄡˋ"]}] },
  "museum": { s:[{zh:"博物館",z:["ㄅㄛˊ","ㄨˋ","ㄍㄨㄢˇ"]}] },
  "dinosaur": { s:[{zh:"恐龍",z:["ㄎㄨㄥˇ","ㄌㄨㄥˊ"]}] },
  "drawing": { s:[{zh:"畫畫",z:["ㄏㄨㄚˋ","ㄏㄨㄚˋ"]}] },
  "model": { s:[{zh:"模型",z:["ㄇㄛˊ","ㄒㄧㄥˊ"]}] },
  "fossil": { s:[{zh:"化石",z:["ㄏㄨㄚˋ","ㄕˊ"]}] },
  "alive": { s:[{zh:"活著的",z:["ㄏㄨㄛˊ","ㄓㄜ˙","ㄉㄜ˙"]}] },
  "trip": { s:[{zh:"旅行",z:["ㄌㄩˇ","ㄒㄧㄥˊ"]}] },
  "break": { s:[{zh:"休息",z:["ㄒㄧㄡ","ㄒㄧˊ"]}] },
  "cow": { s:[{zh:"母牛",z:["ㄇㄨˇ","ㄋㄧㄡˊ"]}] },
  "together": { s:[{zh:"一起",z:["ㄧˋ","ㄑㄧˇ"]}] },
  "puzzle": { s:[{zh:"拼圖",z:["ㄆㄧㄣ","ㄊㄨˊ"]}] },
  "about": { s:[{zh:"關於",z:["ㄍㄨㄢ","ㄩˊ"]}] },
  "could": { s:[{zh:"可以",z:["ㄎㄜˇ","ㄧˇ"]}] },
  "show": { s:[{zh:"顯示",z:["ㄒㄧㄢˇ","ㄕˋ"]}] },
  "chicken": { s:[{zh:"雞",z:["ㄐㄧ"]}] },
  "four": { s:[{zh:"四",z:["ㄙˋ"]}] },
  "bird": { s:[{zh:"鳥",z:["ㄋㄧㄠˇ"]}] },
  "claw": { s:[{zh:"爪子",z:["ㄓㄨㄚˇ","ㄗ˙"]}] },
  "horn": { s:[{zh:"角",z:["ㄐㄧㄠˇ"]}] },
  "teeth": { s:[{zh:"牙齒",z:["ㄧㄚˊ","ㄔˇ"]}] },
  "ate": { s:[{zh:"吃",z:["ㄔ"],note:"過去式"}] },
  "clue": { s:[{zh:"線索",z:["ㄒㄧㄢˋ","ㄙㄨㄛˇ"]}] },
  "flat": { s:[{zh:"平的",z:["ㄆㄧㄥˊ","ㄉㄜ˙"]}] },
  "other": { s:[{zh:"其他的",z:["ㄑㄧˊ","ㄊㄚ","ㄉㄜ˙"]}] },
  "meat": { s:[{zh:"肉",z:["ㄖㄡˋ"]}] },
  "past": { s:[{zh:"過去",z:["ㄍㄨㄛˋ","ㄑㄩˋ"]}] },
  "sky": { s:[{zh:"天空",z:["ㄊㄧㄢ","ㄎㄨㄥ"]}] },
  "cloud": { s:[{zh:"雲",z:["ㄩㄣˊ"]}] },
  "float": { s:[{zh:"漂浮",z:["ㄆㄧㄠ","ㄈㄨˊ"]}] },
  "plane": { s:[{zh:"飛機",z:["ㄈㄟ","ㄐㄧ"]}] },
  "over": { s:[{zh:"在……上方",z:["ㄗㄞˋ","","","ㄕㄤˋ","ㄈㄤ"]}] },
  "stretch": { s:[{zh:"伸展",z:["ㄕㄣ","ㄓㄢˇ"]}] },
  "pilot": { s:[{zh:"飛行員",z:["ㄈㄟ","ㄒㄧㄥˊ","ㄩㄢˊ"]}] },
  "doctor": { s:[{zh:"醫生",z:["ㄧ","ㄕㄥ"]}] },
  "silly": { s:[{zh:"傻的",z:["ㄕㄚˇ","ㄉㄜ˙"]}] },
  "train": { s:[{zh:"火車",z:["ㄏㄨㄛˇ","ㄔㄜ"]},{zh:"訓練",z:["ㄒㄩㄣˋ","ㄌㄧㄢˋ"]}] },
  "neighbor": { s:[{zh:"鄰居",z:["ㄌㄧㄣˊ","ㄐㄩ"]}] },
  "ask": { s:[{zh:"問",z:["ㄨㄣˋ"]}] },
  "tough": { s:[{zh:"堅強的",z:["ㄐㄧㄢ","ㄑㄧㄤˊ","ㄉㄜ˙"]}] },
  "brave": { s:[{zh:"勇敢的",z:["ㄩㄥˇ","ㄍㄢˇ","ㄉㄜ˙"]}] },
  "remind": { s:[{zh:"提醒",z:["ㄊㄧˊ","ㄒㄧㄥˇ"]}] },
  "talented": { s:[{zh:"有天賦的",z:["ㄧㄡˇ","ㄊㄧㄢ","ㄈㄨˋ","ㄉㄜ˙"]}] },
  "wait": { s:[{zh:"等待",z:["ㄉㄥˇ","ㄉㄞˋ"]}] },
  "minute": { s:[{zh:"分鐘",z:["ㄈㄣ","ㄓㄨㄥ"]}] },
  "job": { s:[{zh:"工作",z:["ㄍㄨㄥ","ㄗㄨㄛˋ"]}] },
  "trick": { s:[{zh:"把戲",z:["ㄅㄚˇ","ㄒㄧˋ"]}] },
  "flew": { s:[{zh:"飛",z:["ㄈㄟ"],note:"過去式"}] },
  "start": { s:[{zh:"開始",z:["ㄎㄞ","ㄕˇ"]}] },
  "famous": { s:[{zh:"有名的",z:["ㄧㄡˇ","ㄇㄧㄥˊ","ㄉㄜ˙"]}] },
  "stop": { s:[{zh:"停止",z:["ㄊㄧㄥˊ","ㄓˇ"]}] },
  "elf": { s:[{zh:"精靈",z:["ㄐㄧㄥ","ㄌㄧㄥˊ"]}] },
  "shoemaker": { s:[{zh:"鞋匠",z:["ㄒㄧㄝˊ","ㄐㄧㄤˋ"]}] },
  "leather": { s:[{zh:"皮革",z:["ㄆㄧˊ","ㄍㄜˊ"]}] },
  "shed": { s:[{zh:"小屋",z:["ㄒㄧㄠˇ","ㄨ"]}] },
  "pair": { s:[{zh:"一對",z:["ㄧˊ","ㄉㄨㄟˋ"]}] },
  "shiny": { s:[{zh:"閃亮的",z:["ㄕㄢˇ","ㄌㄧㄤˋ","ㄉㄜ˙"]}] },
  "peek": { s:[{zh:"偷看",z:["ㄊㄡ","ㄎㄢˋ"]}] },
  "Monday": { s:[{zh:"星期一",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄧ"]}] },
  "Tuesday": { s:[{zh:"星期二",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄦˋ"]}] },
  "Wednesday": { s:[{zh:"星期三",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄙㄢ"]}] },
  "Thursday": { s:[{zh:"星期四",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄙˋ"]}] },
  "Friday": { s:[{zh:"星期五",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄨˇ"]}] },
  "Saturday": { s:[{zh:"星期六",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄌㄧㄡˋ"]}] },
  "Sunday": { s:[{zh:"星期日",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄖˋ"]}] },
  "January": { s:[{zh:"一月",z:["ㄧ","ㄩㄝˋ"]}] },
  "February": { s:[{zh:"二月",z:["ㄦˋ","ㄩㄝˋ"]}] },
  "March": { s:[{zh:"三月",z:["ㄙㄢ","ㄩㄝˋ"]}] },
  "April": { s:[{zh:"四月",z:["ㄙˋ","ㄩㄝˋ"]}] },
  "May": { s:[{zh:"五月",z:["ㄨˇ","ㄩㄝˋ"]}] },
  "June": { s:[{zh:"六月",z:["ㄌㄧㄡˋ","ㄩㄝˋ"]}] },
  "July": { s:[{zh:"七月",z:["ㄑㄧ","ㄩㄝˋ"]}] },
  "August": { s:[{zh:"八月",z:["ㄅㄚ","ㄩㄝˋ"]}] },
  "September": { s:[{zh:"九月",z:["ㄐㄧㄡˇ","ㄩㄝˋ"]}] },
  "October": { s:[{zh:"十月",z:["ㄕˊ","ㄩㄝˋ"]}] },
  "November": { s:[{zh:"十一月",z:["ㄕˊ","ㄧ","ㄩㄝˋ"]}] },
  "December": { s:[{zh:"十二月",z:["ㄕˊ","ㄦˋ","ㄩㄝˋ"]}] },

  // ---- 二上（2026-2027 Fall）----
  "shadow": { s:[{zh:"影子",z:["ㄧㄥˇ","ㄗ˙"]}] },
  "meeting": { s:[{zh:"會議",z:["ㄏㄨㄟˋ","ㄧˋ"]}] },
  "nod": { s:[{zh:"點頭",z:["ㄉㄧㄢˇ","ㄊㄡˊ"]}] },
  "colorful": { s:[{zh:"多彩的",z:["ㄉㄨㄛ","ㄘㄞˇ","ㄉㄜ˙"]}] },
  "plant": { s:[{zh:"種植",z:["ㄓㄨㄥˋ","ㄓˊ"]}] },
  "garden": { s:[{zh:"花園",z:["ㄏㄨㄚ","ㄩㄢˊ"]}] },
  "landlord": { s:[{zh:"房東",z:["ㄈㄤˊ","ㄉㄨㄥ"]}] },
  "window box": { s:[{zh:"窗台花箱",z:["ㄔㄨㄤ","ㄊㄞˊ","ㄏㄨㄚ","ㄒㄧㄤ"]}] },
  "soil": { s:[{zh:"土壤",z:["ㄊㄨˇ","ㄖㄤˇ"]}] },
  "elevator": { s:[{zh:"電梯",z:["ㄉㄧㄢˋ","ㄊㄧ"]}] },
  "pour": { s:[{zh:"倒",z:["ㄉㄠˋ"]}] },
  "hang": { s:[{zh:"掛",z:["ㄍㄨㄚˋ"]}] },
  "invite": { s:[{zh:"邀請",z:["ㄧㄠ","ㄑㄧㄥˇ"]}] },
  "scent": { s:[{zh:"香味",z:["ㄒㄧㄤ","ㄨㄟˋ"]}] },
  "joy": { s:[{zh:"喜悅",z:["ㄒㄧˇ","ㄩㄝˋ"]}] },
  "backyard": { s:[{zh:"後院",z:["ㄏㄡˋ","ㄩㄢˋ"]}] },
  "daylight": { s:[{zh:"日光",z:["ㄖˋ","ㄍㄨㄤ"]}] },
  "seaweed": { s:[{zh:"海草",z:["ㄏㄞˇ","ㄘㄠˇ"]}] },
  "snapshot": { s:[{zh:"快照",z:["ㄎㄨㄞˋ","ㄓㄠˋ"]}] },
  "bright": { s:[{zh:"明亮的",z:["ㄇㄧㄥˊ","ㄌㄧㄤˋ","ㄉㄜ˙"]}] },
  "gasp": { s:[{zh:"倒抽一口氣",z:["ㄉㄠˋ","ㄔㄡ","ㄧˋ","ㄎㄡˇ","ㄑㄧˋ"]}] },
  "wink": { s:[{zh:"眨眼",z:["ㄓㄚˇ","ㄧㄢˇ"]}] },
  "arrive": { s:[{zh:"抵達",z:["ㄉㄧˇ","ㄉㄚˊ"]}] },
  "seagull": { s:[{zh:"海鷗",z:["ㄏㄞˇ","ㄡ"]}] },
  "steep": { s:[{zh:"陡峭的",z:["ㄉㄡˇ","ㄑㄧㄠˋ","ㄉㄜ˙"]}] },
  "notice": { s:[{zh:"注意到",z:["ㄓㄨˋ","ㄧˋ","ㄉㄠˋ"]}] },
  "explain": { s:[{zh:"解釋",z:["ㄐㄧㄝˇ","ㄕˋ"]}] },
  "shallow": { s:[{zh:"淺的",z:["ㄑㄧㄢˇ","ㄉㄜ˙"]}] },
  "critter": { s:[{zh:"小動物",z:["ㄒㄧㄠˇ","ㄉㄨㄥˋ","ㄨˋ"]}] },
  "collect": { s:[{zh:"收集",z:["ㄕㄡ","ㄐㄧˊ"]}] },
  "cell phone": { s:[{zh:"手機",z:["ㄕㄡˇ","ㄐㄧ"]}] },
  "creature": { s:[{zh:"生物",z:["ㄕㄥ","ㄨˋ"]}] },
  "hermit crab": { s:[{zh:"寄居蟹",z:["ㄐㄧˋ","ㄐㄩ","ㄒㄧㄝˋ"]}] },
  "explore": { s:[{zh:"探索",z:["ㄊㄢˋ","ㄙㄨㄛˇ"]}] },
  "pleasure": { s:[{zh:"樂趣",z:["ㄌㄜˋ","ㄑㄩˋ"]}] },
  "favorite": { s:[{zh:"最喜愛的",z:["ㄗㄨㄟˋ","ㄒㄧˇ","ㄞˋ","ㄉㄜ˙"]}] },
  "tour": { s:[{zh:"導覽",z:["ㄉㄠˇ","ㄌㄢˇ"]},{zh:"旅行團",z:["ㄌㄩˇ","ㄒㄧㄥˊ","ㄊㄨㄢˊ"]}] },
  "guide": { s:[{zh:"導遊",z:["ㄉㄠˇ","ㄧㄡˊ"]}] },
  "different": { s:[{zh:"不同的",z:["ㄅㄨˋ","ㄊㄨㄥˊ","ㄉㄜ˙"]}] },
  "strange": { s:[{zh:"奇怪的",z:["ㄑㄧˊ","ㄍㄨㄞˋ","ㄉㄜ˙"]}] },
  "cactus": { s:[{zh:"仙人掌",z:["ㄒㄧㄢ","ㄖㄣˊ","ㄓㄤˇ"]}] },
  "vulture": { s:[{zh:"禿鷹",z:["ㄊㄨ","ㄧㄥ"]}] },
  "lizard": { s:[{zh:"蜥蜴",z:["ㄒㄧ","ㄧˋ"]}] },
  "crawl": { s:[{zh:"爬行",z:["ㄆㄚˊ","ㄒㄧㄥˊ"]}] },
  "match": { s:[{zh:"相配",z:["ㄒㄧㄤ","ㄆㄟˋ"]},{zh:"配對",z:["ㄆㄟˋ","ㄉㄨㄟˋ"]}] },
  "fun fact": { s:[{zh:"有趣的小知識",z:["ㄧㄡˇ","ㄑㄩˋ","ㄉㄜ˙","ㄒㄧㄠˇ","ㄓ","ㄕˊ"]}] },
  "lead": { s:[{zh:"帶領",z:["ㄉㄞˋ","ㄌㄧㄥˇ"]}] },
  "assistant": { s:[{zh:"助手",z:["ㄓㄨˋ","ㄕㄡˇ"]}] },
  "decide": { s:[{zh:"決定",z:["ㄐㄩㄝˊ","ㄉㄧㄥˋ"]}] },
  "prairie dog": { s:[{zh:"草原犬鼠",z:["ㄘㄠˇ","ㄩㄢˊ","ㄑㄩㄢˇ","ㄕㄨˇ"]}] },
  "owl": { s:[{zh:"貓頭鷹",z:["ㄇㄠ","ㄊㄡˊ","ㄧㄥ"]}] },
  "coyote": { s:[{zh:"郊狼",z:["ㄐㄧㄠ","ㄌㄤˊ"]}] },
  "pattern": { s:[{zh:"圖案",z:["ㄊㄨˊ","ㄢˋ"]}] },
  "map": { s:[{zh:"地圖",z:["ㄉㄧˋ","ㄊㄨˊ"]}] },
  "alike": { s:[{zh:"相似的",z:["ㄒㄧㄤ","ㄙˋ","ㄉㄜ˙"]}] },
  "Africa": { s:[{zh:"非洲",z:["ㄈㄟ","ㄓㄡ"]}] },
  "Asia": { s:[{zh:"亞洲",z:["ㄧㄚˋ","ㄓㄡ"]}] },
  "Europe": { s:[{zh:"歐洲",z:["ㄡ","ㄓㄡ"]}] },
  "prairie": { s:[{zh:"大草原",z:["ㄉㄚˋ","ㄘㄠˇ","ㄩㄢˊ"]}] },
  "habitat": { s:[{zh:"棲息地",z:["ㄑㄧ","ㄒㄧ","ㄉㄧˋ"]}] },
  "grazer": { s:[{zh:"吃草的動物",z:["ㄔ","ㄘㄠˇ","ㄉㄜ˙","ㄉㄨㄥˋ","ㄨˋ"]}] },
  "burrow": { s:[{zh:"地洞",z:["ㄉㄧˋ","ㄉㄨㄥˋ"]}] },
  "colony": { s:[{zh:"群落",z:["ㄑㄩㄣˊ","ㄌㄨㄛˋ"]}] },
  "grassland": { s:[{zh:"草原",z:["ㄘㄠˇ","ㄩㄢˊ"]}] },
  "bison": { s:[{zh:"野牛",z:["ㄧㄝˇ","ㄋㄧㄡˊ"]}] },
  "hole": { s:[{zh:"洞",z:["ㄉㄨㄥˋ"]}] },
  "badger": { s:[{zh:"獾",z:["ㄏㄨㄢ"]}] },
  "underground": { s:[{zh:"地底",z:["ㄉㄧˋ","ㄉㄧˇ"]}] },
  "hide": { s:[{zh:"躲藏",z:["ㄉㄨㄛˇ","ㄘㄤˊ"]}] },
  "enemy": { s:[{zh:"敵人",z:["ㄉㄧˊ","ㄖㄣˊ"]}] },
  "rattle": { s:[{zh:"發出嘎嘎聲",z:["ㄈㄚ","ㄔㄨ","ㄍㄚ","ㄍㄚ","ㄕㄥ"]}] },
  "hawk": { s:[{zh:"老鷹",z:["ㄌㄠˇ","ㄧㄥ"]}] },
  "ferret": { s:[{zh:"雪貂",z:["ㄒㄩㄝˇ","ㄉㄧㄠ"]}] },
  "exciting": { s:[{zh:"令人興奮的",z:["ㄌㄧㄥˋ","ㄖㄣˊ","ㄒㄧㄥ","ㄈㄣˋ","ㄉㄜ˙"]}] },
  "connect": { s:[{zh:"連接",z:["ㄌㄧㄢˊ","ㄐㄧㄝ"]}] },
  "deer": { s:[{zh:"鹿",z:["ㄌㄨˋ"]}] },
  "slowly": { s:[{zh:"慢慢地",z:["ㄇㄢˋ","ㄇㄢˋ","ㄉㄜ˙"]}] },
  "carefully": { s:[{zh:"小心地",z:["ㄒㄧㄠˇ","ㄒㄧㄣ","ㄉㄜ˙"]}] },
  "quietly": { s:[{zh:"安靜地",z:["ㄢ","ㄐㄧㄥˋ","ㄉㄜ˙"]}] },
  "glow": { s:[{zh:"光芒",z:["ㄍㄨㄤ","ㄇㄤˊ"]}] },
  "rustle": { s:[{zh:"沙沙作響",z:["ㄕㄚ","ㄕㄚ","ㄗㄨㄛˋ","ㄒㄧㄤˇ"]}] },
  "decorate": { s:[{zh:"裝飾",z:["ㄓㄨㄤ","ㄕˋ"]}] },
  "shade": { s:[{zh:"陰涼處",z:["ㄧㄣ","ㄌㄧㄤˊ","ㄔㄨˋ"]}] },
  "swing": { s:[{zh:"鞦韆",z:["ㄑㄧㄡ","ㄑㄧㄢ"]}] },
  "tree house": { s:[{zh:"樹屋",z:["ㄕㄨˋ","ㄨ"]}] },
  "shelter": { s:[{zh:"遮蔽",z:["ㄓㄜ","ㄅㄧˋ"]}] },
  "fort": { s:[{zh:"堡壘",z:["ㄅㄠˇ","ㄌㄟˇ"]}] },
  "company": { s:[{zh:"陪伴",z:["ㄆㄟˊ","ㄅㄢˋ"]},{zh:"公司",z:["ㄍㄨㄥ","ㄙ"]}] },
  "melt": { s:[{zh:"融化",z:["ㄖㄨㄥˊ","ㄏㄨㄚˋ"]}] },
  "honey": { s:[{zh:"蜂蜜",z:["ㄈㄥ","ㄇㄧˋ"]}] },
  "armful": { s:[{zh:"一大抱的",z:["ㄧˊ","ㄉㄚˋ","ㄅㄠˋ","ㄉㄜ˙"]}] },
  "shower": { s:[{zh:"陣雨",z:["ㄓㄣˋ","ㄩˇ"]}] },
  "gather": { s:[{zh:"聚集",z:["ㄐㄩˋ","ㄐㄧˊ"]}] },
  "branch": { s:[{zh:"樹枝",z:["ㄕㄨˋ","ㄓ"]}] },
  "oval": { s:[{zh:"橢圓形的",z:["ㄊㄨㄛˇ","ㄩㄢˊ","ㄒㄧㄥˊ","ㄉㄜ˙"]}] },
  "waddle": { s:[{zh:"搖擺走路",z:["ㄧㄠˊ","ㄅㄞˇ","ㄗㄡˇ","ㄌㄨˋ"]}] },
  "huddle": { s:[{zh:"擠在一起",z:["ㄐㄧˇ","ㄗㄞˋ","ㄧˋ","ㄑㄧˇ"]}] },
  "flock": { s:[{zh:"一群",z:["ㄧˋ","ㄑㄩㄣˊ"]}] },
  "stare": { s:[{zh:"盯著看",z:["ㄉㄧㄥ","ㄓㄜ˙","ㄎㄢˋ"]}] },
  "frown": { s:[{zh:"皺眉",z:["ㄓㄡˋ","ㄇㄟˊ"]}] },
  "tuck": { s:[{zh:"塞進",z:["ㄙㄞ","ㄐㄧㄣˋ"]}] },
  "slide": { s:[{zh:"滑行",z:["ㄏㄨㄚˊ","ㄒㄧㄥˊ"]}] },
  "wander": { s:[{zh:"閒逛",z:["ㄒㄧㄢˊ","ㄍㄨㄤˋ"]}] },
  "cheerful": { s:[{zh:"開朗的",z:["ㄎㄞ","ㄌㄤˇ","ㄉㄜ˙"]}] },
  "forget": { s:[{zh:"忘記",z:["ㄨㄤˋ","ㄐㄧˋ"]}] },
  "storm": { s:[{zh:"暴風雨",z:["ㄅㄠˋ","ㄈㄥ","ㄩˇ"]}] },
  "race": { s:[{zh:"賽跑",z:["ㄙㄞˋ","ㄆㄠˇ"]}] },
  "shield": { s:[{zh:"保護",z:["ㄅㄠˇ","ㄏㄨˋ"]}] },
  "glad": { s:[{zh:"高興的",z:["ㄍㄠ","ㄒㄧㄥˋ","ㄉㄜ˙"]}] },
  "broken": { s:[{zh:"壞掉的",z:["ㄏㄨㄞˋ","ㄉㄧㄠˋ","ㄉㄜ˙"]}] },
  "chick": { s:[{zh:"小雞",z:["ㄒㄧㄠˇ","ㄐㄧ"]}] },
  "sigh": { s:[{zh:"嘆氣",z:["ㄊㄢˋ","ㄑㄧˋ"]}] },
  "huge": { s:[{zh:"巨大的",z:["ㄐㄩˋ","ㄉㄚˋ","ㄉㄜ˙"]}] },
  "reply": { s:[{zh:"回覆",z:["ㄏㄨㄟˊ","ㄈㄨˋ"]}] },
  "holiday": { s:[{zh:"假期",z:["ㄐㄧㄚˋ","ㄑㄧˊ"]}] },
  "souvenir": { s:[{zh:"紀念品",z:["ㄐㄧˋ","ㄋㄧㄢˋ","ㄆㄧㄣˇ"]}] },
  "booth": { s:[{zh:"攤位",z:["ㄊㄢ","ㄨㄟˋ"]}] },
  "outside": { s:[{zh:"在外面",z:["ㄗㄞˋ","ㄨㄞˋ","ㄇㄧㄢˋ"]}] },
  "upset": { s:[{zh:"不高興的",z:["ㄅㄨˋ","ㄍㄠ","ㄒㄧㄥˋ","ㄉㄜ˙"]}] },
  "thought": { s:[{zh:"想法",z:["ㄒㄧㄤˇ","ㄈㄚˇ"]}] },
  "know": { s:[{zh:"知道",z:["ㄓ","ㄉㄠˋ"]}] },
  "believe": { s:[{zh:"相信",z:["ㄒㄧㄤ","ㄒㄧㄣˋ"]}] },
  "only": { s:[{zh:"唯一的",z:["ㄨㄟˊ","ㄧ","ㄉㄜ˙"]}] },
  "suspect": { s:[{zh:"嫌疑犯",z:["ㄒㄧㄢˊ","ㄧˊ","ㄈㄢˋ"]}] },
  "shocked": { s:[{zh:"震驚的",z:["ㄓㄣˋ","ㄐㄧㄥ","ㄉㄜ˙"]}] },
  "disappear": { s:[{zh:"消失",z:["ㄒㄧㄠ","ㄕ"]}] },
  "symbol": { s:[{zh:"符號",z:["ㄈㄨˊ","ㄏㄠˋ"]}] },
  "flour": { s:[{zh:"麵粉",z:["ㄇㄧㄢˋ","ㄈㄣˇ"]}] },
  "worried": { s:[{zh:"擔心的",z:["ㄉㄢ","ㄒㄧㄣ","ㄉㄜ˙"]}] },
  "forgive": { s:[{zh:"原諒",z:["ㄩㄢˊ","ㄌㄧㄤˋ"]}] },
  "solve": { s:[{zh:"解決",z:["ㄐㄧㄝˇ","ㄐㄩㄝˊ"]}] },
  "stealing": { s:[{zh:"偷竊",z:["ㄊㄡ","ㄑㄧㄝˋ"]}] },
  "month": { s:[{zh:"月份",z:["ㄩㄝˋ","ㄈㄣˋ"]}] },
  "fair": { s:[{zh:"公平的",z:["ㄍㄨㄥ","ㄆㄧㄥˊ","ㄉㄜ˙"]}] },
  "planet": { s:[{zh:"行星",z:["ㄒㄧㄥˊ","ㄒㄧㄥ"]}] },
  "surface": { s:[{zh:"表面",z:["ㄅㄧㄠˇ","ㄇㄧㄢˋ"]}] },
  "space": { s:[{zh:"太空",z:["ㄊㄞˋ","ㄎㄨㄥ"]}] },
  "divide": { s:[{zh:"分開",z:["ㄈㄣ","ㄎㄞ"]}] },
  "piece": { s:[{zh:"一塊",z:["ㄧˊ","ㄎㄨㄞˋ"]}] },
  "continent": { s:[{zh:"大陸",z:["ㄉㄚˋ","ㄌㄨˋ"]}] },
  "natural": { s:[{zh:"自然的",z:["ㄗˋ","ㄖㄢˊ","ㄉㄜ˙"]}] },
  "feature": { s:[{zh:"特徵",z:["ㄊㄜˋ","ㄓㄥ"]}] },
  "landform": { s:[{zh:"地形",z:["ㄉㄧˋ","ㄒㄧㄥˊ"]}] },
  "valley": { s:[{zh:"山谷",z:["ㄕㄢ","ㄍㄨˇ"]}] },
  "wide": { s:[{zh:"寬的",z:["ㄎㄨㄢ","ㄉㄜ˙"]}] },
  "island": { s:[{zh:"島嶼",z:["ㄉㄠˇ","ㄩˇ"]}] },
  "flow": { s:[{zh:"流動",z:["ㄌㄧㄡˊ","ㄉㄨㄥˋ"]}] },
  "popular": { s:[{zh:"受歡迎的",z:["ㄕㄡˋ","ㄏㄨㄢ","ㄧㄥˊ","ㄉㄜ˙"]}] },
  "survive": { s:[{zh:"存活",z:["ㄘㄨㄣˊ","ㄏㄨㄛˊ"]}] },
  "salty": { s:[{zh:"鹹的",z:["ㄒㄧㄢˊ","ㄉㄜ˙"]}] },
  "human": { s:[{zh:"人類",z:["ㄖㄣˊ","ㄌㄟˋ"]}] },
  "produce": { s:[{zh:"製造",z:["ㄓˋ","ㄗㄠˋ"]}] },
  "breathe": { s:[{zh:"呼吸",z:["ㄏㄨ","ㄒㄧ"]}] },
  "bottom": { s:[{zh:"底部",z:["ㄉㄧˇ","ㄅㄨˋ"]}] },
  "strong": { s:[{zh:"強壯的",z:["ㄑㄧㄤˊ","ㄓㄨㄤˋ","ㄉㄜ˙"]}] },
  "wave": { s:[{zh:"海浪",z:["ㄏㄞˇ","ㄌㄤˋ"]},{zh:"揮手",z:["ㄏㄨㄟ","ㄕㄡˇ"]}] },
  "hurricane": { s:[{zh:"颶風",z:["ㄐㄩˋ","ㄈㄥ"]}] },
  "cause": { s:[{zh:"造成",z:["ㄗㄠˋ","ㄔㄥˊ"]}] },
  "grow": { s:[{zh:"生長",z:["ㄕㄥ","ㄓㄤˇ"]}] },
  "damage": { s:[{zh:"損害",z:["ㄙㄨㄣˇ","ㄏㄞˋ"]}] },
  "freeze": { s:[{zh:"結冰",z:["ㄐㄧㄝˊ","ㄅㄧㄥ"]}] },
  "thick": { s:[{zh:"厚的",z:["ㄏㄡˋ","ㄉㄜ˙"]}] },
  "dance": { s:[{zh:"舞蹈",z:["ㄨˇ","ㄉㄠˇ"]}] },
  "activity": { s:[{zh:"活動",z:["ㄏㄨㄛˊ","ㄉㄨㄥˋ"]}] },
  "culture": { s:[{zh:"文化",z:["ㄨㄣˊ","ㄏㄨㄚˋ"]}] },
  "begin": { s:[{zh:"開始",z:["ㄎㄞ","ㄕˇ"]}] },
  "traditional": { s:[{zh:"傳統的",z:["ㄔㄨㄢˊ","ㄊㄨㄥˇ","ㄉㄜ˙"]}] },
  "native": { s:[{zh:"原住民的",z:["ㄩㄢˊ","ㄓㄨˋ","ㄇㄧㄣˊ","ㄉㄜ˙"]}] },
  "honor": { s:[{zh:"尊敬",z:["ㄗㄨㄣ","ㄐㄧㄥˋ"]}] },
  "thanks": { s:[{zh:"感謝",z:["ㄍㄢˇ","ㄒㄧㄝˋ"]}] },
  "perform": { s:[{zh:"表演",z:["ㄅㄧㄠˇ","ㄧㄢˇ"]}] },
  "metal": { s:[{zh:"金屬的",z:["ㄐㄧㄣ","ㄕㄨˇ","ㄉㄜ˙"]}] },
  "cone": { s:[{zh:"圓錐",z:["ㄩㄢˊ","ㄓㄨㄟ"]}] },
  "noise": { s:[{zh:"噪音",z:["ㄗㄠˋ","ㄧㄣ"]}] },
  "gathering": { s:[{zh:"聚會",z:["ㄐㄩˋ","ㄏㄨㄟˋ"]}] },
  "American": { s:[{zh:"美國的",z:["ㄇㄟˇ","ㄍㄨㄛˊ","ㄉㄜ˙"]}] },
  "competition": { s:[{zh:"比賽",z:["ㄅㄧˇ","ㄙㄞˋ"]}] },
  "across": { s:[{zh:"橫越",z:["ㄏㄥˊ","ㄩㄝˋ"]}] },
  "fancy": { s:[{zh:"華麗的",z:["ㄏㄨㄚˊ","ㄌㄧˋ","ㄉㄜ˙"]}] },
  "movement": { s:[{zh:"動作",z:["ㄉㄨㄥˋ","ㄗㄨㄛˋ"]}] },
  "smooth": { s:[{zh:"平滑的",z:["ㄆㄧㄥˊ","ㄏㄨㄚˊ","ㄉㄜ˙"]}] },
  "chant": { s:[{zh:"吟唱",z:["ㄧㄣˊ","ㄔㄤˋ"]}] },
  "drum": { s:[{zh:"打鼓",z:["ㄉㄚˇ","ㄍㄨˇ"]}] },
  "necklace": { s:[{zh:"項鍊",z:["ㄒㄧㄤˋ","ㄌㄧㄢˋ"]}] },
  "history": { s:[{zh:"歷史",z:["ㄌㄧˋ","ㄕˇ"]}] },
  "legend": { s:[{zh:"傳說",z:["ㄔㄨㄢˊ","ㄕㄨㄛ"]}] },
  "hula-hoop": { s:[{zh:"呼拉圈",z:["ㄏㄨ","ㄌㄚ","ㄑㄩㄢ"]}] },
  "name after": { s:[{zh:"命名",z:["ㄇㄧㄥˋ","ㄇㄧㄥˊ"]}] },
  "stomp": { s:[{zh:"跺腳",z:["ㄉㄨㄛˋ","ㄐㄧㄠˇ"]}] },
  "heel": { s:[{zh:"腳後跟",z:["ㄐㄧㄠˇ","ㄏㄡˋ","ㄍㄣ"]}] },
  "rhythm": { s:[{zh:"節奏",z:["ㄐㄧㄝˊ","ㄗㄡˋ"]}] },
  "fiddle": { s:[{zh:"小提琴",z:["ㄒㄧㄠˇ","ㄊㄧˊ","ㄑㄧㄣˊ"]}] },
  "be known for": { s:[{zh:"以此聞名",z:["ㄧˇ","ㄘˇ","ㄨㄣˊ","ㄇㄧㄥˊ"]}] },
  "make sense": { s:[{zh:"說得通",z:["ㄕㄨㄛ","ㄉㄜ˙","ㄊㄨㄥ"]}] },
  "present": { s:[{zh:"出席的",z:["ㄔㄨ","ㄒㄧˊ","ㄉㄜ˙"]}] },
  "sugar": { s:[{zh:"糖",z:["ㄊㄤˊ"]}] },
  "cereal": { s:[{zh:"麥片",z:["ㄇㄞˋ","ㄆㄧㄢˋ"]}] },
  "allow": { s:[{zh:"允許",z:["ㄩㄣˇ","ㄒㄩˇ"]}] },
  "adult": { s:[{zh:"大人",z:["ㄉㄚˋ","ㄖㄣˊ"]}] },
  "entire": { s:[{zh:"整個的",z:["ㄓㄥˇ","ㄍㄜˋ","ㄉㄜ˙"]}] },
  "cottage": { s:[{zh:"小屋",z:["ㄒㄧㄠˇ","ㄨ"]}] },
  "general": { s:[{zh:"一般的",z:["ㄧˋ","ㄅㄢ","ㄉㄜ˙"]}] },
  "wonderful": { s:[{zh:"很棒的",z:["ㄏㄣˇ","ㄅㄤˋ","ㄉㄜ˙"]}] },
  "beg": { s:[{zh:"懇求",z:["ㄎㄣˇ","ㄑㄧㄡˊ"]}] },
  "lesson": { s:[{zh:"課",z:["ㄎㄜˋ"]}] },
  "in case": { s:[{zh:"以防萬一",z:["ㄧˇ","ㄈㄤˊ","ㄨㄢˋ","ㄧ"]}] },
  "nervously": { s:[{zh:"緊張地",z:["ㄐㄧㄣˇ","ㄓㄤ","ㄉㄜ˙"]}] },
  "ready": { s:[{zh:"準備好的",z:["ㄓㄨㄣˇ","ㄅㄟˋ","ㄏㄠˇ","ㄉㄜ˙"]}] },
  "exclaim": { s:[{zh:"驚呼",z:["ㄐㄧㄥ","ㄏㄨ"]}] },
  "slip into": { s:[{zh:"換上",z:["ㄏㄨㄢˋ","ㄕㄤˋ"]}] },
  "scared": { s:[{zh:"害怕的",z:["ㄏㄞˋ","ㄆㄚˋ","ㄉㄜ˙"]}] },
  "decision": { s:[{zh:"決定",z:["ㄐㄩㄝˊ","ㄉㄧㄥˋ"]}] },
  "deep": { s:[{zh:"深的",z:["ㄕㄣ","ㄉㄜ˙"]}] },
  "almost": { s:[{zh:"幾乎",z:["ㄐㄧ","ㄏㄨ"]}] },
  "worry": { s:[{zh:"擔心",z:["ㄉㄢ","ㄒㄧㄣ"]}] },
  "proud": { s:[{zh:"驕傲的",z:["ㄐㄧㄠ","ㄠˋ","ㄉㄜ˙"]}] },
  "even though": { s:[{zh:"即使",z:["ㄐㄧˊ","ㄕˇ"]}] },
  "sunscreen": { s:[{zh:"防曬乳",z:["ㄈㄤˊ","ㄕㄞˋ","ㄖㄨˇ"]}] },
  "discover": { s:[{zh:"發現",z:["ㄈㄚ","ㄒㄧㄢˋ"]}] },
  "spine": { s:[{zh:"脊椎",z:["ㄐㄧˇ","ㄓㄨㄟ"]}] },
  "predator": { s:[{zh:"掠食者",z:["ㄌㄩㄝˋ","ㄕˊ","ㄓㄜˇ"]}] },
  "nutrient": { s:[{zh:"養分",z:["ㄧㄤˇ","ㄈㄣˋ"]}] },
  "mammal": { s:[{zh:"哺乳動物",z:["ㄅㄨˇ","ㄖㄨˇ","ㄉㄨㄥˋ","ㄨˋ"]}] },
  "blind": { s:[{zh:"失明的",z:["ㄕ","ㄇㄧㄥˊ","ㄉㄜ˙"]}] },
  "sense": { s:[{zh:"感官",z:["ㄍㄢˇ","ㄍㄨㄢ"]}] },
  "attract": { s:[{zh:"吸引",z:["ㄒㄧ","ㄧㄣˇ"]}] },
  "endangered": { s:[{zh:"瀕臨絕種的",z:["ㄅㄧㄣ","ㄌㄧㄣˊ","ㄐㄩㄝˊ","ㄓㄨㄥˇ","ㄉㄜ˙"]}] }
};

// 倉鼠頁的「先複習本週單字」卡片會用到這兩個。
// （2026-08 遷移 words.js 時漏抽，導致複習卡按「下一個」丟 ReferenceError、
//   淡入動畫永遠沒把卡片設回不透明，畫面看起來全黑。）
const wordImages = {
  "figure out": "🤔",
  "stand up": "🧍",
            "beautiful": "🌸", "calf": "🐄", "graze": "🌾", "forest": "🌳", "angry": "😠", "catch": "⚾", "sad": "😢", "promise": "🤙", "grassy": "🌿", "happy": "😊",
            "agree": "👍", "quickly": "💨", "return": "🔄", "surprised": "😲", "pleased": "😌", "truth": "✅", "mad": "😡", "protect": "🛡️", "always": "♾️", "school": "🏫",
            "learn": "📚", "math": "➕", "problem": "❓", "important": "⭐", "think": "🤔", "art": "🎨", "because": "💬", "creative": "✨", "imagination": "🌈", "amazing": "🤩",
            "music": "🎵", "concentrate": "🧘", "remember": "💡", "teamwork": "🤝", "reason": "🧠", "best": "🥇", "baseball": "⚾", "love": "❤️", "sport": "🏅", "college": "🎓",
            "team": "👥", "allowed": "✅", "meet": "🤝", "field": "🌾", "cheer": "🎉", "boo": "👻", "memory": "🧠", "discovers": "🔍", "amaze": "✨", "wonder": "🌟",
            "tunes": "🎶", "alone": "🧍", "struggle": "💪", "dream": "💭", "achieve": "🏆", "world": "🌍", "whisper": "🤫", "bones": "🦴", "delight": "😄", "children": "👧",
            "mountain": "⛰️", "artist": "🎨", "surround": "🔵", "desert": "🏜️", "season": "🍂", "autumn": "🍁", "spring": "🌸", "summer": "☀️", "winter": "❄️", "speckled": "🥚",
            "woven": "🧺", "showers": "🌧️", "sprout": "🌱", "bloom": "🌺", "spread": "🌊", "slither": "🐍", "barefoot": "🦶", "flutter": "🦋", "taste": "😋", "scurry": "🐭",
            "scatter": "🍃", "jacket": "🧥", "secret": "🤫", "honk": "📯", "store": "🏪", "crisp": "🍏", "gray": "☁️", "rush": "🏃", "spider": "🕷️", "weave": "🕸️",
            "chilly": "🥶", "zip": "🤐", "chipmunk": "🐿️", "dig": "⛏️", "fly": "🦅", "shake": "🫨", "spin": "🌀", "dash": "💨", "empty": "📭", "jar": "🫙",
            "fetch": "🐕", "lie": "🛌", 
            "hard": "🪨", "become": "🦋", "nasty": "🤢", "teammate": "🤝", "stand": "🧍", "admire": "🤩", "die": "🥀",
            "cool": "😎", "fun": "🎠", "mall": "🛒", "picnic": "🧺", "basket": "🛒", "office": "💼", "shop": "🛍️", "fold": "📄",
            "cross": "🚶", "come": "👋", "piano": "🎹", "violin": "🎻", "building": "🏢", "cover": "🍲", "glass": "🪟", "stair": "🪜", "shell": "🐚", "sink": "🚿",
            "visit": "🏡", "community": "🏘️", "bookshelf": "📚", "library": "📖", "real": "👀", "front": "⬆️", "garage": "🚗", "create": "🎨", "elephant": "🐘", "climb": "🧗",
            "country": "🏡", "hear": "👂", "quiet": "🤫", "mouse": "🐭", "letter": "✉️", "cousin": "👨‍👩‍👧", "pick": "🖐️", "excited": "🤩", "imagine": "🌈", "phone": "📱",
            "feet": "🦶", "scary": "👻", "street": "🛣️", "skateboard": "🛹", "zoom": "💨", "shout": "📢", "behind": "🫣", "jump": "🏃", "garbage": "🗑️", "can": "🥫",
            "ambulance": "🚑", "hospital": "🏥", "city": "🌆", "busy": "⏰", "loud": "🔊", "sick": "🤒", "tomorrow": "📅", "soon": "⏳", "later": "🕐", "museum": "🏛️",
            "dinosaur": "🦕", "drawing": "✏️", "model": "✈️", "fossil": "🦴", "alive": "🌱", "trip": "🚌", "break": "☕", "cow": "🐄", "together": "🤝", "puzzle": "🧩",
            "about": "💬", "could": "🙂", "show": "👁️", "chicken": "🐔", "four": "4️⃣", "bird": "🐦", "claw": "🦁", "horn": "🦏", "teeth": "🦷", "ate": "🍽️",
            "clue": "🔍", "flat": "🛣️", "other": "🔁", "meat": "🥩", "past": "⬅️", "sky": "🌤️", "cloud": "☁️", "float": "🎈", "plane": "✈️", "over": "🦅",
            "stretch": "🙆", "pilot": "✈️", "doctor": "👨‍⚕️", "silly": "🤪", "train": "🚂", "neighbor": "🏘️", "ask": "🙋", "tough": "💪", "brave": "🦁", "remind": "🔔",
            "talented": "🎤", "wait": "⏳", "minute": "⏱️", "job": "💼", "trick": "🎩", "flew": "🦅", "start": "🚦", "famous": "⭐", "stop": "🛑", "elf": "🧝",
            "shoemaker": "👞", "leather": "👜", "shed": "🛖", "pair": "👟", "shiny": "✨", "peek": "🙈",
            "Monday": "📅", "Tuesday": "📅", "Wednesday": "📅", "Thursday": "📅", "Friday": "📅", "Saturday": "📅", "Sunday": "📅",
            "January": "❄️", "February": "💝", "March": "🌸", "April": "🌧️", "May": "🌹", "June": "🎓", "July": "☀️", "August": "🏖️", "September": "🍂", "October": "🎃", "November": "🧥", "December": "🎄",
            // ---- 二上 ----
            "shadow": "🌑", "meeting": "📋", "nod": "👌", "colorful": "🌈", "plant": "🌱", "garden": "🌷", "landlord": "🔑", "window box": "🪟",
            "soil": "🟫", "elevator": "🛗", "pour": "🫗", "hang": "🪝", "invite": "💌", "scent": "👃", "joy": "😄", "backyard": "🏡",
            "daylight": "🌞", "seaweed": "🌿", "snapshot": "📸", "bright": "🔆", "gasp": "😮", "wink": "😉", "arrive": "🛬", "seagull": "🕊️",
            "steep": "📈", "notice": "🔎", "explain": "🗣️", "shallow": "💧", "critter": "🐛", "collect": "📦", "cell phone": "📲", "creature": "🦑",
            "hermit crab": "🦀", "explore": "🧭", "pleasure": "😃", "favorite": "💖", "tour": "🎫", "guide": "🧑‍🏫", "different": "🔀", "strange": "🤨",
            "cactus": "🌵", "vulture": "🦅", "lizard": "🦎", "crawl": "🚼", "match": "🟰", "fun fact": "🤓", "lead": "➡️", "assistant": "🧑‍💼",
            "decide": "✔️", "prairie dog": "🐿️", "owl": "🦉", "coyote": "🐺", "pattern": "🔷", "map": "🗺️", "alike": "👯", "Africa": "🌍",
            "Asia": "🌏", "Europe": "🇪🇺", "prairie": "🌾", "habitat": "🏞️", "grazer": "🐐", "burrow": "🕳️", "colony": "🐜", "grassland": "🟩",
            "bison": "🦬", "hole": "⚫", "badger": "🦡", "underground": "⬇️", "hide": "🫥", "enemy": "⚔️", "rattle": "🐍", "hawk": "🦅",
            "ferret": "🐾", "exciting": "🎢", "connect": "🔗", "deer": "🦌", "slowly": "🐢", "carefully": "🧐", "quietly": "🔇", "glow": "🕯️",
            "rustle": "🌬️", "decorate": "🎀", "shade": "⛱️", "swing": "🛝", "tree house": "🌲", "shelter": "⛺", "fort": "🏰", "company": "👫",
            "melt": "🫠", "honey": "🍯", "armful": "🤲", "shower": "🌦️", "gather": "🫂", "branch": "🪵", "oval": "🥚", "waddle": "🐧",
            "huddle": "🤗", "flock": "🐦", "stare": "👀", "frown": "😟", "tuck": "🛏️", "slide": "🛷", "wander": "🚶", "cheerful": "😄",
            "forget": "🤷", "storm": "⛈️", "race": "🏁", "shield": "🛡️", "glad": "😊", "broken": "💔", "chick": "🐣", "sigh": "😮‍💨",
            "huge": "🐋", "reply": "💬", "holiday": "🏖️", "souvenir": "🎁", "booth": "🏪", "outside": "🚪", "upset": "😞", "thought": "💭",
            "know": "🧠", "believe": "🙏", "only": "1️⃣", "suspect": "🕵️", "shocked": "😱", "disappear": "💨", "symbol": "🔣", "flour": "🌾",
            "worried": "😟", "forgive": "🤝", "solve": "🧩", "stealing": "🥷", "month": "🗓️", "fair": "⚖️", "planet": "🪐", "surface": "🌐",
            "space": "🚀", "divide": "➗", "piece": "🧩", "continent": "🌎", "natural": "🍃", "feature": "🔍", "landform": "🏞️", "valley": "🏔️",
            "wide": "↔️", "island": "🏝️", "flow": "🌊", "popular": "🌟", "survive": "💪", "salty": "🧂", "human": "🧑", "produce": "🏭",
            "breathe": "🫁", "bottom": "⬇️", "strong": "💪", "wave": "🌊", "hurricane": "🌀", "cause": "➡️", "grow": "🌱", "damage": "💥",
            "freeze": "🧊", "thick": "📚", "dance": "💃", "activity": "🎯", "culture": "🏮", "begin": "🚦", "traditional": "🎎", "native": "🪶",
            "honor": "🎖️", "thanks": "🙏", "perform": "🎭", "metal": "🔩", "cone": "🔺", "noise": "🔊", "gathering": "👨‍👩‍👧‍👦", "American": "🇺🇸",
            "competition": "🏆", "across": "🌉", "fancy": "💅", "movement": "🕺", "smooth": "🧈", "chant": "🎶", "drum": "🥁", "necklace": "📿",
            "history": "📜", "legend": "🐉", "hula-hoop": "⭕", "name after": "🏷️", "stomp": "👣", "heel": "🦶", "rhythm": "🎵", "fiddle": "🎻",
            "be known for": "⭐", "make sense": "💡", "present": "🙋", "sugar": "🍬", "cereal": "🥣", "allow": "✅", "adult": "🧑", "entire": "💯",
            "cottage": "🏡", "general": "📋", "wonderful": "🤩", "beg": "🙇", "lesson": "📖", "in case": "☂️", "nervously": "😬", "ready": "🏁",
            "exclaim": "❗", "slip into": "👕", "scared": "😨", "decision": "🤔", "deep": "🌊", "almost": "🔜", "worry": "😟", "proud": "🦚",
            "even though": "🔀", "sunscreen": "🧴", "discover": "🔍", "spine": "🦴", "predator": "🦁", "nutrient": "🥗", "mammal": "🐻", "blind": "🦯",
            "sense": "👂", "attract": "🧲", "endangered": "🐼"
        };

const wordExamples = {
  "figure out": "I can figure out the answer.",
  "stand up": "Please stand up.",
            "beautiful": "The flower is beautiful.", "calf": "The calf follows its mother.", "graze": "Cows graze in the field.", "forest": "Animals live in the forest.", "angry": "He is angry at the dog.", "catch": "She can catch the ball.", "sad": "The boy is sad today.", "promise": "I promise to be kind.", "grassy": "We played on the grassy hill.", "happy": "She is happy to see you.",
            "agree": "I agree with you!", "quickly": "She ran quickly to school.", "return": "He will return home soon.", "surprised": "She was surprised by the gift.", "pleased": "Mom is pleased with the work.", "truth": "Always tell the truth.", "mad": "He felt mad all day.", "protect": "Dogs protect their owners.", "always": "I always brush my teeth.", "school": "She loves going to school.",
            "learn": "We learn new words every day.", "math": "Math class is fun!", "problem": "She solved the hard problem.", "important": "Reading is very important.", "think": "Think before you speak.", "art": "He loves to make art.", "because": "She smiled because she was happy.", "creative": "The child is very creative.", "imagination": "Use your imagination to draw!", "amazing": "The magic show is amazing!",
            "music": "She plays music on the piano.", "concentrate": "Please concentrate on your work.", "remember": "Remember to drink water.", "teamwork": "Good teamwork wins the game.", "reason": "What is the reason you are late?", "best": "She did her best.", "baseball": "He hits the baseball far.", "love": "I love my family.", "sport": "Which sport do you like?", "college": "She studies at college.",
            "team": "Our team won the game!", "allowed": "You are allowed to use a pencil.", "meet": "We meet at the park.", "field": "The cows are in the field.", "cheer": "The crowd will cheer for us.", "boo": "They started to boo the player.", "memory": "She has a great memory.", "discovers": "He discovers a new bug.", "amaze": "The trick will amaze you!", "wonder": "I wonder what is inside.",
            "tunes": "She hummed her favorite tunes.", "alone": "He sat alone under the tree.", "struggle": "She had to struggle to carry the box.", "dream": "I have a big dream!", "achieve": "Work hard to achieve your goal.", "world": "We live in a wonderful world.", "whisper": "She gave a soft whisper.", "bones": "Dogs love to chew on bones.", "delight": "The cake was pure delight.", "children": "The children played in the park.",
            "mountain": "The mountain is very tall.", "artist": "He is a great artist.", "surround": "Trees surround the little house.", "desert": "The desert is hot and dry.", "season": "Which season do you like most?", "autumn": "Leaves fall in autumn.", "spring": "Flowers bloom in spring.", "summer": "We swim in summer.", "winter": "We wear hats in winter.", "speckled": "The egg is speckled with brown dots.",
            "woven": "She wore a woven hat.", "showers": "April showers bring May flowers.", "sprout": "The seeds begin to sprout.", "bloom": "Roses bloom in the garden.", "spread": "The butter spread on the toast.", "slither": "Snakes slither on the ground.", "barefoot": "She ran barefoot on the grass.", "flutter": "Butterflies flutter from flower to flower.", "taste": "This apple has a sweet taste.", "scurry": "Mice scurry across the floor.",
            "scatter": "The wind will scatter the leaves.", "jacket": "Wear a jacket when it is cold.", "secret": "They shared a secret.", "honk": "The car went honk honk!", "store": "Let's go to the store for milk.", "crisp": "The air is crisp in autumn.", "gray": "The sky is gray before it rains.", "rush": "We rush to catch the bus.", "spider": "A spider spun a web.", "weave": "Spiders weave silk webs.",
            "chilly": "The morning is chilly.", "zip": "Zip up your jacket!", "chipmunk": "A chipmunk hid its food.", "dig": "Dogs love to dig holes.", "fly": "Birds can fly very high.", "shake": "Shake the bottle before drinking.", "spin": "The top began to spin.", "dash": "She made a dash for the door.", "empty": "The glass is empty.", "jar": "There is honey in the jar.",
            "fetch": "The dog will fetch the ball.", "lie": "She likes to lie on the grass.", 
            "hard": "The rock is very hard.", "become": "The caterpillar will become a butterfly.", "nasty": "That was a nasty storm.", "teammate": "He is a good teammate.", "stand": "Please stand up when the teacher comes in.", "admire": "I admire your beautiful painting.", "die": "Plants will die without water.",
            "cool": "The breeze feels cool.", "fun": "Swimming is so much fun!", "mall": "We went to the mall on Saturday.", "picnic": "We had a picnic in the park.", "basket": "She put apples in the basket.", "office": "Dad works in an office.", "shop": "Let's shop for shoes today.", "fold": "Please fold the paper in half.",
            "cross": "Look both ways before you cross the street.", "come": "Come and play with me!", "piano": "She plays the piano every day.", "violin": "He plays the violin at school.", "building": "The building is very tall.", "cover": "Cover the pot with a lid.", "glass": "The window is made of glass.", "stair": "Climb the stair to the top.", "shell": "She found a shell at the beach.", "sink": "Wash your hands in the sink.",
            "visit": "We visit grandma on Sunday.", "community": "Everyone helped their community.", "bookshelf": "Fill the bookshelf with books.", "library": "We borrowed books from the library.", "real": "Is that a real butterfly?", "front": "She sat in the front row.", "garage": "Dad parks the car in the garage.", "create": "She used clay to create a pot.", "elephant": "The elephant has a long trunk.", "climb": "He can climb the tall tree.",
            "country": "They live in the country.", "hear": "I can hear the birds sing.", "quiet": "Please be quiet in the library.", "mouse": "The mouse ran under the table.", "letter": "She wrote a letter to her friend.", "cousin": "My cousin lives far away.", "pick": "Pick the ripe apples first.", "excited": "She is so excited to go!", "imagine": "Imagine a land made of candy.", "phone": "Call me on the phone!",
            "feet": "She dipped her feet in the river.", "scary": "The dark cave is scary.", "street": "Our dog walked down the street.", "skateboard": "He loves to ride his skateboard.", "zoom": "The car zoomed past us!", "shout": "Don't shout in the classroom!", "behind": "She hid behind the tree.", "jump": "Jump over the puddle!", "garbage": "Put the garbage in the bin.", "can": "She can swim very well.",
            "ambulance": "The ambulance rushed to the hospital.", "hospital": "The nurse works at the hospital.", "city": "The city has many tall buildings.", "busy": "Mom is very busy today.", "loud": "The music was too loud.", "sick": "He stayed home because he was sick.", "tomorrow": "We will go to the zoo tomorrow.", "soon": "Lunch will be ready soon.", "later": "I will call you later.", "museum": "We saw dinosaur bones at the museum.",
            "dinosaur": "A dinosaur lived long long ago.", "drawing": "She made a lovely drawing.", "model": "He built a model airplane.", "fossil": "They found a fossil in the rock.", "alive": "Plants need water to stay alive.", "trip": "We went on a trip to the beach.", "break": "Let's take a break and drink water.", "cow": "The cow says moo!", "together": "Let's do it together!", "puzzle": "Can you solve the puzzle?",
            "about": "Tell me about your day.", "could": "She could ride a bike.", "show": "Can you show me how to do it?", "chicken": "The chicken laid an egg.", "four": "I have four books.", "bird": "A little bird sat on the branch.", "claw": "The cat stretched out its claw.", "horn": "The rhino has a big horn.", "teeth": "Brush your teeth twice a day.", "ate": "She ate all her vegetables.",
            "clue": "Look for a clue to solve the mystery.", "flat": "The road is flat and smooth.", "other": "Do you have any other ideas?", "meat": "The lion hunts for meat.", "past": "Walk past the red building.", "sky": "The sky is bright blue.", "cloud": "That cloud looks like a fluffy sheep!", "float": "Watch the balloon float away.", "plane": "The plane flew above the clouds.", "over": "She jumped over the puddle.",
            "stretch": "Stretch your arms up high!", "pilot": "The pilot flew the plane.", "doctor": "The doctor helped me feel better.", "silly": "He made a silly face.", "train": "The train went choo choo!", "neighbor": "Our neighbor baked us cookies.", "ask": "Ask your teacher if you need help.", "tough": "It was a tough race but she won!", "brave": "The brave girl spoke in front of the class.", "remind": "Remind me to buy milk.",
            "talented": "She is a very talented singer.", "wait": "Wait for the green light.", "minute": "I will be there in one minute.", "job": "His job is to take care of animals.", "trick": "The magician did a cool trick.", "flew": "The bird flew over the mountain.", "start": "Ready, set, start!", "famous": "She is a famous author.", "stop": "Stop at the red light.", "elf": "An elf helped the shoemaker.",
            "shoemaker": "The shoemaker made shoes all day.", "leather": "The bag is made of leather.", "shed": "Grandpa kept tools in the shed.", "pair": "She bought a new pair of shoes.", "shiny": "The star was shiny and bright.", "peek": "She peeked through the curtain.",
            "Monday": "School starts on Monday.", "Tuesday": "We have P.E. on Tuesday.", "Wednesday": "Wednesday is in the middle of the week.", "Thursday": "I have piano class on Thursday.", "Friday": "Friday is my favorite day!", "Saturday": "We go to the park on Saturday.", "Sunday": "Sunday is a day to rest.",
            "January": "January is the first month.", "February": "Valentine's Day is in February.", "March": "Spring begins in March.", "April": "April showers bring May flowers.", "May": "Mother's Day is in May.", "June": "School ends in June.", "July": "July is very hot!", "August": "We go to the beach in August.", "September": "Leaves fall in September.", "October": "Halloween is in October.", "November": "November is chilly.", "December": "Christmas is in December!",
            // ---- 二上 ----
            "shadow": "The tree makes a long shadow.", "meeting": "We had a class meeting today.", "nod": "She will nod to say yes.", "colorful": "The garden is very colorful.",
            "plant": "Let's plant seeds in the box.", "garden": "Grandma works in her garden.", "landlord": "The landlord opened the door.", "window box": "Flowers grow in the window box.",
            "soil": "Put the soil in the pot.", "elevator": "We rode the elevator to the top.", "pour": "Pour the water on the plant.", "hang": "Hang your coat on the hook.",
            "invite": "I will invite my friends over.", "scent": "The flowers have a sweet scent.", "joy": "The song filled her with joy.", "backyard": "We play in the backyard.",
            "daylight": "We walked home in the daylight.", "seaweed": "Seaweed floats in the sea.", "snapshot": "Dad took a snapshot of us.", "bright": "The sun is very bright today.",
            "gasp": "She gave a gasp of surprise.", "wink": "He gave me a friendly wink.", "arrive": "We arrive at school at eight.", "seagull": "A seagull flew over the boat.",
            "steep": "The path up the hill is steep.", "notice": "Did you notice the new sign?", "explain": "Please explain the game to me.", "shallow": "The pool is shallow here.",
            "critter": "A tiny critter hid in the sand.", "collect": "I collect shells at the beach.", "cell phone": "Mom called on her cell phone.", "creature": "The sea has many creatures.",
            "hermit crab": "A hermit crab lives in a shell.", "explore": "Let's explore the rock pool.", "pleasure": "Reading gives me great pleasure.", "favorite": "Blue is my favorite color.",
            "tour": "We went on a tour of the zoo.", "guide": "The guide showed us the way.", "different": "These two hats are different.", "strange": "I heard a strange sound.",
            "cactus": "A cactus grows in the desert.", "vulture": "A vulture sat on the rock.", "lizard": "The lizard ran up the wall.", "crawl": "The baby can crawl very fast.",
            "match": "Your socks do not match!", "fun fact": "Here is a fun fact about bats.", "lead": "Please lead the way.", "assistant": "The assistant helped the teacher.",
            "decide": "You decide which book to read.", "prairie dog": "A prairie dog popped up.", "owl": "The owl hunts at night.", "coyote": "A coyote howled far away.",
            "pattern": "Her dress has a pretty pattern.", "map": "We found the park on the map.", "alike": "The twins look alike.", "Africa": "Lions live in Africa.",
            "Asia": "Taiwan is in Asia.", "Europe": "France is in Europe.", "prairie": "Bison walk across the prairie.", "habitat": "The prairie is their habitat.",
            "grazer": "A bison is a big grazer.", "burrow": "The rabbit ran into its burrow.", "colony": "Ants live in a big colony.", "grassland": "Zebras run on the grassland.",
            "bison": "A bison eats grass all day.", "hole": "There is a hole in my sock.", "badger": "A badger digs with its claws.", "underground": "Prairie dogs sleep underground.",
            "hide": "Let's hide behind the tree.", "enemy": "The hawk is their enemy.", "rattle": "The snake began to rattle.", "hawk": "A hawk flew over the field.",
            "ferret": "A ferret has a long body.", "exciting": "The trip was very exciting!", "connect": "The tunnels connect the holes.", "deer": "A deer ate leaves by the road.",
            "slowly": "The turtle walks slowly.", "carefully": "Carry the eggs carefully.", "quietly": "She closed the door quietly.", "glow": "The candle gave a soft glow.",
            "rustle": "The leaves rustle in the wind.", "decorate": "We decorate the tree together.", "shade": "We sat in the shade.", "swing": "She likes the swing in the park.",
            "tree house": "Dad built us a tree house.", "shelter": "The branches shelter the birds.", "fort": "We made a fort out of boxes.", "company": "Thank you for your company.",
            "melt": "The snow will melt in spring.", "honey": "Bees make sweet honey.", "armful": "She carried an armful of apples.", "shower": "A shower fell on the garden.",
            "gather": "We gather apples every fall.", "branch": "A bird sat on the branch.", "oval": "The egg is oval.", "waddle": "Penguins waddle on the ice.",
            "huddle": "They huddle to keep warm.", "flock": "A flock of birds flew by.", "stare": "Don't stare at people.", "frown": "She began to frown at the rain.",
            "tuck": "Tuck the egg under your feet.", "slide": "Penguins slide on their bellies.", "wander": "Do not wander far from home.", "cheerful": "She has a cheerful smile.",
            "forget": "Don't forget your lunch box!", "storm": "A big storm is coming.", "race": "They race back to the nest.", "shield": "The wings shield the chick.",
            "glad": "I am glad you are here.", "broken": "The egg shell is broken.", "chick": "The chick is out of the egg!", "sigh": "He let out a long sigh.",
            "huge": "The Sphinx is huge!", "reply": "She did not reply to my letter.", "holiday": "We go to Egypt on our holiday.", "souvenir": "I bought a souvenir for Mom.",
            "booth": "He sells hats at the booth.", "outside": "The kids are playing outside.", "upset": "He was upset about the news.", "thought": "I had a funny thought.",
            "know": "I know the answer!", "believe": "I believe you can do it.", "only": "She is the only girl here.", "suspect": "The police found the suspect.",
            "shocked": "We were shocked by the noise.", "disappear": "The cat seemed to disappear.", "symbol": "A heart is a symbol of love.", "flour": "Add flour to make the bread.",
            "worried": "Mom looked worried.", "forgive": "Please forgive me.", "solve": "Can you solve the mystery?", "stealing": "Stealing is wrong.",
            "month": "May is my favorite month.", "fair": "That is not fair!", "planet": "Earth is our planet.", "surface": "Water covers most of the surface.",
            "space": "We can see Earth from space.", "divide": "Divide the cake into four.", "piece": "May I have a piece of bread?", "continent": "Asia is the biggest continent.",
            "natural": "A valley is a natural landform.", "feature": "A long neck is its best feature.", "landform": "A mountain is a landform.", "valley": "A river runs through the valley.",
            "wide": "The ocean is very wide.", "island": "Taiwan is an island.", "flow": "Rivers flow to the sea.", "popular": "This beach is very popular.",
            "survive": "Fish cannot survive out of water.", "salty": "Sea water is salty.", "human": "Every human needs clean water.", "produce": "Plants produce the air we breathe.",
            "breathe": "Whales come up to breathe.", "bottom": "Shells sit on the bottom of the sea.", "strong": "The wind is very strong.", "wave": "A big wave hit the boat.",
            "hurricane": "A hurricane blew the roof away.", "cause": "Storms cause big waves.", "grow": "Waves grow taller in a storm.", "damage": "The flood will damage the town.",
            "freeze": "The lake will freeze in winter.", "thick": "The ice is thick and hard.", "dance": "This dance is from Mexico.", "activity": "Dancing is a fun activity.",
            "culture": "Food is part of our culture.", "begin": "The show will begin soon.", "traditional": "She wore a traditional dress.", "native": "This is a native dance.",
            "honor": "The dance honors their grandparents.", "thanks": "They give thanks for the rain.", "perform": "They perform on the big stage.", "metal": "The dress has metal cones.",
            "cone": "Each cone makes a small sound.", "noise": "The drums make a loud noise.", "gathering": "The whole town came to the gathering.", "American": "It is an American dance.",
            "competition": "She won the dance competition.", "across": "People dance across the country.", "fancy": "He wore a fancy shirt.", "movement": "Every movement tells a story.",
            "smooth": "The floor is smooth and shiny.", "chant": "The dancers chant together.", "drum": "He will drum for the dancers.", "necklace": "Her necklace is made of shells.",
            "history": "This dance has a long history.", "legend": "The dance tells an old legend.", "hula-hoop": "She can spin a hula-hoop.", "name after": "They name the dance after a bird.",
            "stomp": "The dancers stomp their feet.", "heel": "Tap the floor with your heel.", "rhythm": "Clap to the rhythm of the song.", "fiddle": "He plays a lively fiddle.",
            "be known for": "Ireland is known for this dance.", "make sense": "Now the story makes sense!", "present": "All the dancers are present.", "sugar": "Put sugar in the tea.",
            "cereal": "I eat cereal for breakfast.", "allow": "Mom will allow me to swim.", "adult": "An adult must come with you.", "entire": "She swam the entire lake!",
            "cottage": "We stayed in a small cottage.", "general": "This is the general rule.", "wonderful": "What a wonderful day!", "beg": "I beg you to let me try.",
            "lesson": "I have a swimming lesson today.", "in case": "Take a coat in case it rains.", "nervously": "She waited nervously at the start.", "ready": "Are you ready to swim?",
            "exclaim": "\"I did it!\" she exclaimed.", "slip into": "She slipped into her swimsuit.", "scared": "He was scared of the deep water.", "decision": "It was a hard decision.",
            "deep": "The lake is very deep.", "almost": "We are almost there!", "worry": "Don't worry about the test.", "proud": "Mom is proud of me.",
            "even though": "She swam even though it was cold.", "sunscreen": "Put on sunscreen before you swim.", "discover": "Scientists discover new animals.", "spine": "A mole has a strong spine.",
            "predator": "An owl is a predator.", "nutrient": "Roots take nutrients from the soil.", "mammal": "A bat is a mammal.", "blind": "Moles are almost blind.",
            "sense": "Bats use their sense of hearing.", "attract": "Flowers attract bees.", "endangered": "Pandas are an endangered animal."
        };

// ---- 以下都是推導出來的，不要手動維護 ----

// 遊戲讀的還是這個扁平結構，所以四個遊戲一行都不用改。
// 順序：本學期 -> 常用 -> 以前學過的（新的在前）
function activeTerm() {
  if (curriculum[CURRENT_TERM]) return CURRENT_TERM;
  // 很容易先把 CURRENT_TERM 改成新學期、資料卻還沒貼進來。
  // 沒有這個保護的話，本學期的清單會整個消失而且不會報錯。
  const fallback = Object.keys(curriculum).sort().pop();
  if (typeof console !== "undefined") {
    console.warn(`words.js: CURRENT_TERM "${CURRENT_TERM}" 在 curriculum 裡找不到，暫時改用 "${fallback}"`);
  }
  return fallback;
}

// 每個清單都標學期，本學期的也標 —— 不然「FET Spelling」到底是哪一學期
// 的看不出來，而她同時看得到兩個學期的清單。
function buildWords() {
  const out = {};
  const active = activeTerm();
  const cur = curriculum[active];
  if (cur) for (const [list, weeks] of Object.entries(cur.lists)) out[`${cur.label} · ${list}`] = weeks;
  for (const [name, weeks] of Object.entries(evergreen)) out[name] = weeks;
  for (const [term, t] of Object.entries(curriculum).sort().reverse()) {
    if (term === active) continue;
    for (const [list, weeks] of Object.entries(t.lists)) out[`${t.label} · ${list}`] = weeks;
  }
  return out;
}

const words = buildWords();

// 一個字出自哪些地方。即時推導，加學期時不會有一份資料忘了同步。
function wordSources(word) {
  const w = String(word).toLowerCase();
  const hits = [];
  const scan = (prefix, lists) => {
    for (const [list, weeks] of Object.entries(lists))
      for (const [wk, ws] of Object.entries(weeks))
        if (ws.some((x) => x.toLowerCase() === w))
          hits.push({ term: prefix.term, label: prefix.label, list, week: wk,
                      text: (prefix.label ? prefix.label + " · " : "") + list + " / " + wk });
  };
  for (const [term, t] of Object.entries(curriculum)) scan({ term, label: t.label }, t.lists);
  scan({ term: null, label: "" }, evergreen);
  return hits;
}

function isCurrentTerm(word) {
  const active = activeTerm();
  return wordSources(word).some((s) => s.term === active || s.term === null);
}

// ---- 向後相容層：組回舊的 "中文 (ㄅㄆㄇ)" 字串 ----
function formatSense(s) {
  const zy = s.z.filter(Boolean).join(" ");
  return s.zh + (zy ? " (" + zy + ")" : "") + (s.note ? "〔" + s.note + "〕" : "");
}

const wordTranslations = {};
for (const [w, e] of Object.entries(wordEntries)) {
  const text = e.s.map(formatSense).join(" / ");
  wordTranslations[w] = text;
  // 遊戲是用 wordTranslations[word.toLowerCase()] 查表，但 Monday~Sunday /
  // January~December 這 19 個 key 是大寫開頭，原本永遠查不到。補上小寫別名。
  wordTranslations[w.toLowerCase()] = text;
}

function lookupWord(word) {
  const w = String(word).trim();
  return wordEntries[w] || wordEntries[w.toLowerCase()] ||
         Object.entries(wordEntries).find(([k]) => k.toLowerCase() === w.toLowerCase())?.[1] || null;
}
