// Daisy 單字資料
// wordEntries 是主資料：每個單字可有多個義項，每個義項的注音逐字對齊。
// wordTranslations 由 wordEntries 自動產生，僅為了讓既有遊戲不用改就能跑。

const words = {
            "FET Spelling": {
                "Wk 2": ["beautiful", "calf", "graze", "forest", "angry", "catch", "sad", "promise", "grassy", "happy"],
                "Wk 3": ["agree", "quickly", "return", "surprised", "pleased", "truth", "mad", "protect", "always", "promise"],
                "Wk 4": ["school", "learn", "math", "problem", "important", "think", "art", "because", "creative", "imagination"],
                "Wk 5": ["amazing", "music", "concentrate", "remember", "teamwork", "reason", "best", "learn"],
                "Wk 6": ["baseball", "love", "sport", "college", "team", "allowed", "meet", "field", "cheer", "boo"],
                "Wk 7": ["hard", "season", "become", "nasty", "teammate", "stand", "admire", "die", "baseball", "sport"],
                "Wk 10": ["memory", "discovers", "amaze", "wonder", "tunes", "alone", "struggle", "dream", "achieve", "world"],
                "Wk 11/12": ["wonder", "whisper", "bones", "delight", "children", "mountain", "artist", "surround", "desert", "season"],
                "Wk 13": ["autumn", "spring", "summer", "winter", "speckled", "woven", "showers", "sprout", "bloom", "spread"],
                "Wk 14": ["slither", "barefoot", "flutter", "taste", "scurry", "scatter", "jacket", "secret", "honk", "store"],
                "Wk 15": ["crisp", "gray", "rush", "spider", "weave", "chilly", "zip", "agree", "chipmunk", "dig"],
                "Wk 16": ["autumn", "whisper", "fly", "shake", "spin", "dash", "empty", "jar", "fetch", "lie"]
            },
            "常用單字": {
                "星期": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
                "月份": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
            },
            "CET Vocabulary": {
                "Wk 1&2": ["cool", "fun", "world", "mall", "picnic", "basket", "office", "shop", "fold", "cross"],
                "Wk 3": ["come", "piano", "violin", "music", "building", "cover", "glass", "stair", "shell", "sink"],
                "Wk 4": ["visit", "community", "bookshelf", "library", "real", "front", "garage", "create", "elephant", "climb"],
                "Wk 5": ["country", "hear", "quiet", "mouse", "letter", "cousin", "pick", "excited", "imagine", "phone"],
                "Wk 6": ["feet", "scary", "street", "skateboard", "zoom", "shout", "behind", "jump", "garbage", "can"],
                "Wk 7&8": ["ambulance", "hospital", "city", "busy", "loud", "sick", "tomorrow", "soon", "later"],
                "Wk 10": ["field", "museum", "dinosaur", "drawing", "model", "fossil", "alive", "trip", "break"],
                "Wk 11": ["cow", "together", "puzzle", "about", "could", "show", "chicken", "four", "bird"],
                "Wk 12": ["claw", "catch", "horn", "teeth", "ate", "clue", "flat", "other", "meat", "past"],
                "Wk 13": ["sky", "cloud", "float", "plane", "over", "dream", "stretch", "pilot", "doctor", "silly"],
                "Wk 14": ["train", "neighbor", "ask", "tough", "brave", "remind", "talented", "wait", "minute", "job"],
                "Wk 15&16": ["trick", "fly", "flew", "learn", "start", "famous", "stop"],
                "Wk 18": ["elf", "shoemaker", "imagination", "leather", "shed", "pair", "shiny", "peek"]
            }
        };

const wordEntries = {
  "beautiful": { s:[{zh:"美麗的",z:["ㄇㄟˇ","ㄌㄧˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 2"] },
  "calf": { s:[{zh:"小牛",z:["ㄒㄧㄠˇ","ㄋㄧㄡˊ"]}], src:["FET Spelling / Wk 2"] },
  "graze": { s:[{zh:"吃草",z:["ㄔ","ㄘㄠˇ"]}], src:["FET Spelling / Wk 2"] },
  "forest": { s:[{zh:"森林",z:["ㄙㄣ","ㄌㄧㄣˊ"]}], src:["FET Spelling / Wk 2"] },
  "angry": { s:[{zh:"生氣的",z:["ㄕㄥ","ㄑㄧˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 2"] },
  "catch": { s:[{zh:"抓",z:["ㄓㄨㄚ"]}], src:["FET Spelling / Wk 2","CET Vocabulary / Wk 12"] },
  "sad": { s:[{zh:"難過的",z:["ㄋㄢˊ","ㄍㄨㄛˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 2"] },
  "promise": { s:[{zh:"答應",z:["ㄉㄚ","ㄧㄥˋ"]}], src:["FET Spelling / Wk 2","FET Spelling / Wk 3"] },
  "grassy": { s:[{zh:"長滿草的",z:["ㄓㄤˇ","ㄇㄢˇ","ㄘㄠˇ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 2"] },
  "happy": { s:[{zh:"快樂的",z:["ㄎㄨㄞˋ","ㄌㄜˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 2"] },
  "agree": { s:[{zh:"同意",z:["ㄊㄨㄥˊ","ㄧˋ"]}], src:["FET Spelling / Wk 3","FET Spelling / Wk 15"] },
  "quickly": { s:[{zh:"快速地",z:["ㄎㄨㄞˋ","ㄙㄨˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 3"] },
  "return": { s:[{zh:"返回",z:["ㄈㄢˇ","ㄏㄨㄟˊ"]}], src:["FET Spelling / Wk 3"] },
  "surprised": { s:[{zh:"驚訝的",z:["ㄐㄧㄥ","ㄧㄚˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 3"] },
  "pleased": { s:[{zh:"高興的",z:["ㄍㄠ","ㄒㄧㄥˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 3"] },
  "truth": { s:[{zh:"真相",z:["ㄓㄣ","ㄒㄧㄤˋ"]}], src:["FET Spelling / Wk 3"] },
  "mad": { s:[{zh:"生氣的",z:["ㄕㄥ","ㄑㄧˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 3"] },
  "protect": { s:[{zh:"保護",z:["ㄅㄠˇ","ㄏㄨˋ"]}], src:["FET Spelling / Wk 3"] },
  "always": { s:[{zh:"總是",z:["ㄗㄨㄥˇ","ㄕˋ"]}], src:["FET Spelling / Wk 3"] },
  "school": { s:[{zh:"學校",z:["ㄒㄩㄝˊ","ㄒㄧㄠˋ"]}], src:["FET Spelling / Wk 4"] },
  "learn": { s:[{zh:"學習",z:["ㄒㄩㄝˊ","ㄒㄧˊ"]}], src:["FET Spelling / Wk 4","FET Spelling / Wk 5","CET Vocabulary / Wk 15&16"] },
  "math": { s:[{zh:"數學",z:["ㄕㄨˋ","ㄒㄩㄝˊ"]}], src:["FET Spelling / Wk 4"] },
  "problem": { s:[{zh:"問題",z:["ㄨㄣˋ","ㄊㄧˊ"]}], src:["FET Spelling / Wk 4"] },
  "important": { s:[{zh:"重要的",z:["ㄓㄨㄥˋ","ㄧㄠˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 4"] },
  "think": { s:[{zh:"思考",z:["ㄙ","ㄎㄠˇ"]}], src:["FET Spelling / Wk 4"] },
  "art": { s:[{zh:"藝術",z:["ㄧˋ","ㄕㄨˋ"]}], src:["FET Spelling / Wk 4"] },
  "because": { s:[{zh:"因為",z:["ㄧㄣ","ㄨㄟˋ"]}], src:["FET Spelling / Wk 4"] },
  "creative": { s:[{zh:"有創意的",z:["ㄧㄡˇ","ㄔㄨㄤˋ","ㄧˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 4"] },
  "imagination": { s:[{zh:"想像力",z:["ㄒㄧㄤˇ","ㄒㄧㄤˋ","ㄌㄧˋ"]}], src:["FET Spelling / Wk 4","CET Vocabulary / Wk 18"] },
  "amazing": { s:[{zh:"驚人的",z:["ㄐㄧㄥ","ㄖㄣˊ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 5"] },
  "music": { s:[{zh:"音樂",z:["ㄧㄣ","ㄩㄝˋ"]}], src:["FET Spelling / Wk 5","CET Vocabulary / Wk 3"] },
  "concentrate": { s:[{zh:"專心",z:["ㄓㄨㄢ","ㄒㄧㄣ"]}], src:["FET Spelling / Wk 5"] },
  "remember": { s:[{zh:"記得",z:["ㄐㄧˋ","ㄉㄜˊ"]}], src:["FET Spelling / Wk 5"] },
  "teamwork": { s:[{zh:"團隊合作",z:["ㄊㄨㄢˊ","ㄉㄨㄟˋ","ㄏㄜˊ","ㄗㄨㄛˋ"]}], src:["FET Spelling / Wk 5"] },
  "reason": { s:[{zh:"理由",z:["ㄌㄧˇ","ㄧㄡˊ"]}], src:["FET Spelling / Wk 5"] },
  "best": { s:[{zh:"最好的",z:["ㄗㄨㄟˋ","ㄏㄠˇ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 5"] },
  "baseball": { s:[{zh:"棒球",z:["ㄅㄤˋ","ㄑㄧㄡˊ"]}], src:["FET Spelling / Wk 6","FET Spelling / Wk 7"] },
  "love": { s:[{zh:"愛",z:["ㄞˋ"]}], src:["FET Spelling / Wk 6"] },
  "sport": { s:[{zh:"運動",z:["ㄩㄣˋ","ㄉㄨㄥˋ"]}], src:["FET Spelling / Wk 6","FET Spelling / Wk 7"] },
  "college": { s:[{zh:"大學",z:["ㄉㄚˋ","ㄒㄩㄝˊ"]}], src:["FET Spelling / Wk 6"] },
  "team": { s:[{zh:"隊伍",z:["ㄉㄨㄟˋ","ㄨˇ"]}], src:["FET Spelling / Wk 6"] },
  "allowed": { s:[{zh:"允許的",z:["ㄩㄣˇ","ㄒㄩˇ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 6"] },
  "meet": { s:[{zh:"遇見",z:["ㄩˋ","ㄐㄧㄢˋ"]}], src:["FET Spelling / Wk 6"] },
  "field": { s:[{zh:"原野",z:["ㄩㄢˊ","ㄧㄝˇ"]},{zh:"球場",z:["ㄑㄧㄡˊ","ㄔㄤˇ"]}], src:["FET Spelling / Wk 6","CET Vocabulary / Wk 10"] },
  "cheer": { s:[{zh:"歡呼",z:["ㄏㄨㄢ","ㄏㄨ"]}], src:["FET Spelling / Wk 6"] },
  "boo": { s:[{zh:"噓聲",z:["ㄒㄩ","ㄕㄥ"]}], src:["FET Spelling / Wk 6"] },
  "memory": { s:[{zh:"記憶",z:["ㄐㄧˋ","ㄧˋ"]}], src:["FET Spelling / Wk 10"] },
  "discovers": { s:[{zh:"發現",z:["ㄈㄚ","ㄒㄧㄢˋ"]}], src:["FET Spelling / Wk 10"] },
  "amaze": { s:[{zh:"使驚訝",z:["ㄕˇ","ㄐㄧㄥ","ㄧㄚˋ"]}], src:["FET Spelling / Wk 10"] },
  "wonder": { s:[{zh:"奇蹟",z:["ㄑㄧˊ","ㄐㄧ"]},{zh:"想知道",z:["ㄒㄧㄤˇ","ㄓ","ㄉㄠˋ"]}], src:["FET Spelling / Wk 10","FET Spelling / Wk 11/12"] },
  "tunes": { s:[{zh:"曲調",z:["ㄑㄩˇ","ㄉㄧㄠˋ"]}], src:["FET Spelling / Wk 10"] },
  "alone": { s:[{zh:"單獨的",z:["ㄉㄢ","ㄉㄨˊ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 10"] },
  "struggle": { s:[{zh:"掙扎",z:["ㄓㄥ","ㄓㄚˊ"]}], src:["FET Spelling / Wk 10"] },
  "dream": { s:[{zh:"夢想",z:["ㄇㄥˋ","ㄒㄧㄤˇ"]}], src:["FET Spelling / Wk 10","CET Vocabulary / Wk 13"] },
  "achieve": { s:[{zh:"達成",z:["ㄉㄚˊ","ㄔㄥˊ"]}], src:["FET Spelling / Wk 10"] },
  "world": { s:[{zh:"世界",z:["ㄕˋ","ㄐㄧㄝˋ"]}], src:["FET Spelling / Wk 10","CET Vocabulary / Wk 1&2"] },
  "whisper": { s:[{zh:"耳語",z:["ㄦˇ","ㄩˇ"]}], src:["FET Spelling / Wk 11/12","FET Spelling / Wk 16"] },
  "bones": { s:[{zh:"骨頭",z:["ㄍㄨˇ","ㄊㄡ˙"]}], src:["FET Spelling / Wk 11/12"] },
  "delight": { s:[{zh:"愉快",z:["ㄩˊ","ㄎㄨㄞˋ"]}], src:["FET Spelling / Wk 11/12"] },
  "children": { s:[{zh:"孩子們",z:["ㄏㄞˊ","ㄗ˙","ㄇㄣ˙"]}], src:["FET Spelling / Wk 11/12"] },
  "mountain": { s:[{zh:"山",z:["ㄕㄢ"]}], src:["FET Spelling / Wk 11/12"] },
  "artist": { s:[{zh:"藝術家",z:["ㄧˋ","ㄕㄨˋ","ㄐㄧㄚ"]}], src:["FET Spelling / Wk 11/12"] },
  "surround": { s:[{zh:"圍繞",z:["ㄨㄟˊ","ㄖㄠˋ"]}], src:["FET Spelling / Wk 11/12"] },
  "desert": { s:[{zh:"沙漠",z:["ㄕㄚ","ㄇㄛˋ"]}], src:["FET Spelling / Wk 11/12"] },
  "season": { s:[{zh:"季節",z:["ㄐㄧˋ","ㄐㄧㄝˊ"]}], src:["FET Spelling / Wk 7","FET Spelling / Wk 11/12"] },
  "autumn": { s:[{zh:"秋天",z:["ㄑㄧㄡ","ㄊㄧㄢ"]}], src:["FET Spelling / Wk 13","FET Spelling / Wk 16"] },
  "spring": { s:[{zh:"春天",z:["ㄔㄨㄣ","ㄊㄧㄢ"]}], src:["FET Spelling / Wk 13"] },
  "summer": { s:[{zh:"夏天",z:["ㄒㄧㄚˋ","ㄊㄧㄢ"]}], src:["FET Spelling / Wk 13"] },
  "winter": { s:[{zh:"冬天",z:["ㄉㄨㄥ","ㄊㄧㄢ"]}], src:["FET Spelling / Wk 13"] },
  "speckled": { s:[{zh:"有斑點的",z:["ㄧㄡˇ","ㄅㄢ","ㄉㄧㄢˇ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 13"] },
  "woven": { s:[{zh:"編織的",z:["ㄅㄧㄢ","ㄓ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 13"] },
  "showers": { s:[{zh:"陣雨",z:["ㄓㄣˋ","ㄩˇ"]}], src:["FET Spelling / Wk 13"] },
  "sprout": { s:[{zh:"發芽",z:["ㄈㄚ","ㄧㄚˊ"]}], src:["FET Spelling / Wk 13"] },
  "bloom": { s:[{zh:"開花",z:["ㄎㄞ","ㄏㄨㄚ"]}], src:["FET Spelling / Wk 13"] },
  "spread": { s:[{zh:"傳播",z:["ㄔㄨㄢˊ","ㄅㄛˋ"]}], src:["FET Spelling / Wk 13"] },
  "slither": { s:[{zh:"滑行",z:["ㄏㄨㄚˊ","ㄒㄧㄥˊ"]}], src:["FET Spelling / Wk 14"] },
  "barefoot": { s:[{zh:"赤腳",z:["ㄔˋ","ㄐㄧㄠˇ"]}], src:["FET Spelling / Wk 14"] },
  "flutter": { s:[{zh:"拍翅",z:["ㄆㄞ","ㄔˋ"]}], src:["FET Spelling / Wk 14"] },
  "taste": { s:[{zh:"味道",z:["ㄨㄟˋ","ㄉㄠˋ"]}], src:["FET Spelling / Wk 14"] },
  "scurry": { s:[{zh:"碎步快跑",z:["ㄙㄨㄟˋ","ㄅㄨˋ","ㄎㄨㄞˋ","ㄆㄠˇ"]}], src:["FET Spelling / Wk 14"] },
  "scatter": { s:[{zh:"散開",z:["ㄙㄢˋ","ㄎㄞ"]}], src:["FET Spelling / Wk 14"] },
  "jacket": { s:[{zh:"夾克",z:["ㄐㄧㄚˊ","ㄎㄜˋ"]}], src:["FET Spelling / Wk 14"] },
  "secret": { s:[{zh:"秘密",z:["ㄇㄧˋ","ㄇㄧˋ"]}], src:["FET Spelling / Wk 14"] },
  "honk": { s:[{zh:"喇叭聲",z:["ㄌㄚˇ","ㄅㄚ","ㄕㄥ"]}], src:["FET Spelling / Wk 14"] },
  "store": { s:[{zh:"商店",z:["ㄕㄤ","ㄉㄧㄢˋ"]}], src:["FET Spelling / Wk 14"] },
  "crisp": { s:[{zh:"清爽的",z:["ㄑㄧㄥ","ㄕㄨㄤˇ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 15"] },
  "gray": { s:[{zh:"灰色的",z:["ㄏㄨㄟ","ㄙㄜˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 15"] },
  "rush": { s:[{zh:"急動",z:["ㄐㄧˊ","ㄉㄨㄥˋ"]}], src:["FET Spelling / Wk 15"] },
  "spider": { s:[{zh:"蜘蛛",z:["ㄓ","ㄓㄨ"]}], src:["FET Spelling / Wk 15"] },
  "weave": { s:[{zh:"編織",z:["ㄅㄧㄢ","ㄓ"]}], src:["FET Spelling / Wk 15"] },
  "chilly": { s:[{zh:"寒冷的",z:["ㄏㄢˊ","ㄌㄥˇ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 15"] },
  "zip": { s:[{zh:"拉鍊",z:["ㄌㄚ","ㄌㄧㄢˋ"]}], src:["FET Spelling / Wk 15"] },
  "chipmunk": { s:[{zh:"花栗鼠",z:["ㄏㄨㄚ","ㄌㄧˋ","ㄕㄨˇ"]}], src:["FET Spelling / Wk 15"] },
  "dig": { s:[{zh:"挖",z:["ㄨㄚ"]}], src:["FET Spelling / Wk 15"] },
  "fly": { s:[{zh:"飛",z:["ㄈㄟ"]}], src:["FET Spelling / Wk 16","CET Vocabulary / Wk 15&16"] },
  "shake": { s:[{zh:"搖動",z:["ㄧㄠˊ","ㄉㄨㄥˋ"]}], src:["FET Spelling / Wk 16"] },
  "spin": { s:[{zh:"旋轉",z:["ㄒㄩㄢˊ","ㄓㄨㄢˇ"]}], src:["FET Spelling / Wk 16"] },
  "dash": { s:[{zh:"衝刺",z:["ㄔㄨㄥ","ㄘˋ"]}], src:["FET Spelling / Wk 16"] },
  "empty": { s:[{zh:"空的",z:["ㄎㄨㄥ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 16"] },
  "jar": { s:[{zh:"罐子",z:["ㄍㄨㄢˋ","ㄗ˙"]}], src:["FET Spelling / Wk 16"] },
  "fetch": { s:[{zh:"拿來",z:["ㄋㄚˊ","ㄌㄞˊ"]}], src:["FET Spelling / Wk 16"] },
  "lie": { s:[{zh:"躺",z:["ㄊㄤˇ"]},{zh:"說謊",z:["ㄕㄨㄛ","ㄏㄨㄤˇ"]}], src:["FET Spelling / Wk 16"] },
  "hard": { s:[{zh:"困難的",z:["ㄎㄨㄣˋ","ㄋㄢˊ","ㄉㄜ˙"]},{zh:"硬的",z:["ㄧㄥˋ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 7"] },
  "become": { s:[{zh:"變成",z:["ㄅㄧㄢˋ","ㄔㄥˊ"]}], src:["FET Spelling / Wk 7"] },
  "nasty": { s:[{zh:"糟糕的",z:["ㄗㄠ","ㄍㄠ","ㄉㄜ˙"]}], src:["FET Spelling / Wk 7"] },
  "teammate": { s:[{zh:"隊友",z:["ㄉㄨㄟˋ","ㄧㄡˇ"]}], src:["FET Spelling / Wk 7"] },
  "stand": { s:[{zh:"站起來",z:["ㄓㄢˋ","ㄑㄧˇ","ㄌㄞˊ"]}], src:["FET Spelling / Wk 7"] },
  "admire": { s:[{zh:"欣賞",z:["ㄒㄧㄣ","ㄕㄤˇ"]},{zh:"欽佩",z:["ㄑㄧㄣ","ㄆㄟˋ"]}], src:["FET Spelling / Wk 7"] },
  "die": { s:[{zh:"死亡",z:["ㄙˇ","ㄨㄤˊ"]}], src:["FET Spelling / Wk 7"] },
  "cool": { s:[{zh:"酷的",z:["ㄎㄨˋ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 1&2"] },
  "fun": { s:[{zh:"有趣的",z:["ㄧㄡˇ","ㄑㄩˋ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 1&2"] },
  "mall": { s:[{zh:"購物中心",z:["ㄍㄡˋ","ㄨˋ","ㄓㄨㄥ","ㄒㄧㄣ"]}], src:["CET Vocabulary / Wk 1&2"] },
  "picnic": { s:[{zh:"野餐",z:["ㄧㄝˇ","ㄘㄢ"]}], src:["CET Vocabulary / Wk 1&2"] },
  "basket": { s:[{zh:"籃子",z:["ㄌㄢˊ","ㄗ˙"]}], src:["CET Vocabulary / Wk 1&2"] },
  "office": { s:[{zh:"辦公室",z:["ㄅㄢˋ","ㄍㄨㄥ","ㄕˋ"]}], src:["CET Vocabulary / Wk 1&2"] },
  "shop": { s:[{zh:"商店",z:["ㄕㄤ","ㄉㄧㄢˋ"]}], src:["CET Vocabulary / Wk 1&2"] },
  "fold": { s:[{zh:"摺疊",z:["ㄓㄜˊ","ㄉㄧㄝˊ"]}], src:["CET Vocabulary / Wk 1&2"] },
  "cross": { s:[{zh:"越過",z:["ㄩㄝˋ","ㄍㄨㄛˋ"]}], src:["CET Vocabulary / Wk 1&2"] },
  "come": { s:[{zh:"來",z:["ㄌㄞˊ"]}], src:["CET Vocabulary / Wk 3"] },
  "piano": { s:[{zh:"鋼琴",z:["ㄍㄤ","ㄑㄧㄣˊ"]}], src:["CET Vocabulary / Wk 3"] },
  "violin": { s:[{zh:"小提琴",z:["ㄒㄧㄠˇ","ㄊㄧˊ","ㄑㄧㄣˊ"]}], src:["CET Vocabulary / Wk 3"] },
  "building": { s:[{zh:"建築物",z:["ㄐㄧㄢˋ","ㄓㄨˊ","ㄨˋ"]}], src:["CET Vocabulary / Wk 3"] },
  "cover": { s:[{zh:"覆蓋",z:["ㄈㄨˋ","ㄍㄞˋ"]}], src:["CET Vocabulary / Wk 3"] },
  "glass": { s:[{zh:"玻璃",z:["ㄅㄛ","ㄌㄧˊ"]}], src:["CET Vocabulary / Wk 3"] },
  "stair": { s:[{zh:"樓梯",z:["ㄌㄡˊ","ㄊㄧ"]}], src:["CET Vocabulary / Wk 3"] },
  "shell": { s:[{zh:"貝殼",z:["ㄅㄟˋ","ㄎㄜˊ"]}], src:["CET Vocabulary / Wk 3"] },
  "sink": { s:[{zh:"水槽",z:["ㄕㄨㄟˇ","ㄘㄠˊ"]}], src:["CET Vocabulary / Wk 3"] },
  "visit": { s:[{zh:"拜訪",z:["ㄅㄞˋ","ㄈㄤˇ"]}], src:["CET Vocabulary / Wk 4"] },
  "community": { s:[{zh:"社區",z:["ㄕㄜˋ","ㄑㄩ"]}], src:["CET Vocabulary / Wk 4"] },
  "bookshelf": { s:[{zh:"書架",z:["ㄕㄨ","ㄐㄧㄚˋ"]}], src:["CET Vocabulary / Wk 4"] },
  "library": { s:[{zh:"圖書館",z:["ㄊㄨˊ","ㄕㄨ","ㄍㄨㄢˇ"]}], src:["CET Vocabulary / Wk 4"] },
  "real": { s:[{zh:"真實的",z:["ㄓㄣ","ㄕˊ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 4"] },
  "front": { s:[{zh:"前面",z:["ㄑㄧㄢˊ","ㄇㄧㄢˋ"]}], src:["CET Vocabulary / Wk 4"] },
  "garage": { s:[{zh:"車庫",z:["ㄔㄜ","ㄎㄨˋ"]}], src:["CET Vocabulary / Wk 4"] },
  "create": { s:[{zh:"創造",z:["ㄔㄨㄤˋ","ㄗㄠˋ"]}], src:["CET Vocabulary / Wk 4"] },
  "elephant": { s:[{zh:"大象",z:["ㄉㄚˋ","ㄒㄧㄤˋ"]}], src:["CET Vocabulary / Wk 4"] },
  "climb": { s:[{zh:"爬",z:["ㄆㄚˊ"]}], src:["CET Vocabulary / Wk 4"] },
  "country": { s:[{zh:"國家",z:["ㄍㄨㄛˊ","ㄐㄧㄚ"]},{zh:"鄉村",z:["ㄒㄧㄤ","ㄘㄨㄣ"]}], src:["CET Vocabulary / Wk 5"] },
  "hear": { s:[{zh:"聽見",z:["ㄊㄧㄥ","ㄐㄧㄢˋ"]}], src:["CET Vocabulary / Wk 5"] },
  "quiet": { s:[{zh:"安靜的",z:["ㄢ","ㄐㄧㄥˋ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 5"] },
  "mouse": { s:[{zh:"老鼠",z:["ㄌㄠˇ","ㄕㄨˇ"]}], src:["CET Vocabulary / Wk 5"] },
  "letter": { s:[{zh:"信",z:["ㄒㄧㄣˋ"]},{zh:"字母",z:["ㄗˋ","ㄇㄨˇ"]}], src:["CET Vocabulary / Wk 5"] },
  "cousin": { s:[{zh:"堂表親",z:["ㄊㄤˊ","ㄅㄧㄠˇ","ㄑㄧㄣ"]}], src:["CET Vocabulary / Wk 5"] },
  "pick": { s:[{zh:"撿",z:["ㄐㄧㄢˇ"]}], src:["CET Vocabulary / Wk 5"] },
  "excited": { s:[{zh:"興奮的",z:["ㄒㄧㄥ","ㄈㄣˋ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 5"] },
  "imagine": { s:[{zh:"想像",z:["ㄒㄧㄤˇ","ㄒㄧㄤˋ"]}], src:["CET Vocabulary / Wk 5"] },
  "phone": { s:[{zh:"電話",z:["ㄉㄧㄢˋ","ㄏㄨㄚˋ"]}], src:["CET Vocabulary / Wk 5"] },
  "feet": { s:[{zh:"腳",z:["ㄐㄧㄠˇ"]}], src:["CET Vocabulary / Wk 6"] },
  "scary": { s:[{zh:"可怕的",z:["ㄎㄜˇ","ㄆㄚˋ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 6"] },
  "street": { s:[{zh:"街道",z:["ㄐㄧㄝ","ㄉㄠˋ"]}], src:["CET Vocabulary / Wk 6"] },
  "skateboard": { s:[{zh:"滑板",z:["ㄏㄨㄚˊ","ㄅㄢˇ"]}], src:["CET Vocabulary / Wk 6"] },
  "zoom": { s:[{zh:"快速移動",z:["ㄎㄨㄞˋ","ㄙㄨˋ","ㄧˊ","ㄉㄨㄥˋ"]}], src:["CET Vocabulary / Wk 6"] },
  "shout": { s:[{zh:"大喊",z:["ㄉㄚˋ","ㄏㄢˇ"]}], src:["CET Vocabulary / Wk 6"] },
  "behind": { s:[{zh:"在……後面",z:["ㄗㄞˋ","","","ㄏㄡˋ","ㄇㄧㄢ˙"]}], src:["CET Vocabulary / Wk 6"] },
  "jump": { s:[{zh:"跳",z:["ㄊㄧㄠˋ"]}], src:["CET Vocabulary / Wk 6"] },
  "garbage": { s:[{zh:"垃圾",z:["ㄌㄜˋ","ㄙㄜˋ"]}], src:["CET Vocabulary / Wk 6"] },
  "can": { s:[{zh:"可以",z:["ㄎㄜˇ","ㄧˇ"]},{zh:"罐子",z:["ㄍㄨㄢˋ","ㄗ˙"]}], src:["CET Vocabulary / Wk 6"] },
  "ambulance": { s:[{zh:"救護車",z:["ㄐㄧㄡˋ","ㄏㄨˋ","ㄔㄜ"]}], src:["CET Vocabulary / Wk 7&8"] },
  "hospital": { s:[{zh:"醫院",z:["ㄧ","ㄩㄢˋ"]}], src:["CET Vocabulary / Wk 7&8"] },
  "city": { s:[{zh:"城市",z:["ㄔㄥˊ","ㄕˋ"]}], src:["CET Vocabulary / Wk 7&8"] },
  "busy": { s:[{zh:"忙碌的",z:["ㄇㄤˊ","ㄌㄨˋ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 7&8"] },
  "loud": { s:[{zh:"大聲的",z:["ㄉㄚˋ","ㄕㄥ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 7&8"] },
  "sick": { s:[{zh:"生病的",z:["ㄕㄥ","ㄅㄧㄥˋ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 7&8"] },
  "tomorrow": { s:[{zh:"明天",z:["ㄇㄧㄥˊ","ㄊㄧㄢ"]}], src:["CET Vocabulary / Wk 7&8"] },
  "soon": { s:[{zh:"很快地",z:["ㄏㄣˇ","ㄎㄨㄞˋ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 7&8"] },
  "later": { s:[{zh:"稍後",z:["ㄕㄠ","ㄏㄡˋ"]}], src:["CET Vocabulary / Wk 7&8"] },
  "museum": { s:[{zh:"博物館",z:["ㄅㄛˊ","ㄨˋ","ㄍㄨㄢˇ"]}], src:["CET Vocabulary / Wk 10"] },
  "dinosaur": { s:[{zh:"恐龍",z:["ㄎㄨㄥˇ","ㄌㄨㄥˊ"]}], src:["CET Vocabulary / Wk 10"] },
  "drawing": { s:[{zh:"畫畫",z:["ㄏㄨㄚˋ","ㄏㄨㄚˋ"]}], src:["CET Vocabulary / Wk 10"] },
  "model": { s:[{zh:"模型",z:["ㄇㄛˊ","ㄒㄧㄥˊ"]}], src:["CET Vocabulary / Wk 10"] },
  "fossil": { s:[{zh:"化石",z:["ㄏㄨㄚˋ","ㄕˊ"]}], src:["CET Vocabulary / Wk 10"] },
  "alive": { s:[{zh:"活著的",z:["ㄏㄨㄛˊ","ㄓㄜ˙","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 10"] },
  "trip": { s:[{zh:"旅行",z:["ㄌㄩˇ","ㄒㄧㄥˊ"]}], src:["CET Vocabulary / Wk 10"] },
  "break": { s:[{zh:"休息",z:["ㄒㄧㄡ","ㄒㄧˊ"]}], src:["CET Vocabulary / Wk 10"] },
  "cow": { s:[{zh:"母牛",z:["ㄇㄨˇ","ㄋㄧㄡˊ"]}], src:["CET Vocabulary / Wk 11"] },
  "together": { s:[{zh:"一起",z:["ㄧˋ","ㄑㄧˇ"]}], src:["CET Vocabulary / Wk 11"] },
  "puzzle": { s:[{zh:"拼圖",z:["ㄆㄧㄣ","ㄊㄨˊ"]}], src:["CET Vocabulary / Wk 11"] },
  "about": { s:[{zh:"關於",z:["ㄍㄨㄢ","ㄩˊ"]}], src:["CET Vocabulary / Wk 11"] },
  "could": { s:[{zh:"可以",z:["ㄎㄜˇ","ㄧˇ"]}], src:["CET Vocabulary / Wk 11"] },
  "show": { s:[{zh:"顯示",z:["ㄒㄧㄢˇ","ㄕˋ"]}], src:["CET Vocabulary / Wk 11"] },
  "chicken": { s:[{zh:"雞",z:["ㄐㄧ"]}], src:["CET Vocabulary / Wk 11"] },
  "four": { s:[{zh:"四",z:["ㄙˋ"]}], src:["CET Vocabulary / Wk 11"] },
  "bird": { s:[{zh:"鳥",z:["ㄋㄧㄠˇ"]}], src:["CET Vocabulary / Wk 11"] },
  "claw": { s:[{zh:"爪子",z:["ㄓㄨㄚˇ","ㄗ˙"]}], src:["CET Vocabulary / Wk 12"] },
  "horn": { s:[{zh:"角",z:["ㄐㄧㄠˇ"]}], src:["CET Vocabulary / Wk 12"] },
  "teeth": { s:[{zh:"牙齒",z:["ㄧㄚˊ","ㄔˇ"]}], src:["CET Vocabulary / Wk 12"] },
  "ate": { s:[{zh:"吃",z:["ㄔ"],note:"過去式"}], src:["CET Vocabulary / Wk 12"] },
  "clue": { s:[{zh:"線索",z:["ㄒㄧㄢˋ","ㄙㄨㄛˇ"]}], src:["CET Vocabulary / Wk 12"] },
  "flat": { s:[{zh:"平的",z:["ㄆㄧㄥˊ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 12"] },
  "other": { s:[{zh:"其他的",z:["ㄑㄧˊ","ㄊㄚ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 12"] },
  "meat": { s:[{zh:"肉",z:["ㄖㄡˋ"]}], src:["CET Vocabulary / Wk 12"] },
  "past": { s:[{zh:"過去",z:["ㄍㄨㄛˋ","ㄑㄩˋ"]}], src:["CET Vocabulary / Wk 12"] },
  "sky": { s:[{zh:"天空",z:["ㄊㄧㄢ","ㄎㄨㄥ"]}], src:["CET Vocabulary / Wk 13"] },
  "cloud": { s:[{zh:"雲",z:["ㄩㄣˊ"]}], src:["CET Vocabulary / Wk 13"] },
  "float": { s:[{zh:"漂浮",z:["ㄆㄧㄠ","ㄈㄨˊ"]}], src:["CET Vocabulary / Wk 13"] },
  "plane": { s:[{zh:"飛機",z:["ㄈㄟ","ㄐㄧ"]}], src:["CET Vocabulary / Wk 13"] },
  "over": { s:[{zh:"在……上方",z:["ㄗㄞˋ","","","ㄕㄤˋ","ㄈㄤ"]}], src:["CET Vocabulary / Wk 13"] },
  "stretch": { s:[{zh:"伸展",z:["ㄕㄣ","ㄓㄢˇ"]}], src:["CET Vocabulary / Wk 13"] },
  "pilot": { s:[{zh:"飛行員",z:["ㄈㄟ","ㄒㄧㄥˊ","ㄩㄢˊ"]}], src:["CET Vocabulary / Wk 13"] },
  "doctor": { s:[{zh:"醫生",z:["ㄧ","ㄕㄥ"]}], src:["CET Vocabulary / Wk 13"] },
  "silly": { s:[{zh:"傻的",z:["ㄕㄚˇ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 13"] },
  "train": { s:[{zh:"火車",z:["ㄏㄨㄛˇ","ㄔㄜ"]}], src:["CET Vocabulary / Wk 14"] },
  "neighbor": { s:[{zh:"鄰居",z:["ㄌㄧㄣˊ","ㄐㄩ"]}], src:["CET Vocabulary / Wk 14"] },
  "ask": { s:[{zh:"問",z:["ㄨㄣˋ"]}], src:["CET Vocabulary / Wk 14"] },
  "tough": { s:[{zh:"堅強的",z:["ㄐㄧㄢ","ㄑㄧㄤˊ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 14"] },
  "brave": { s:[{zh:"勇敢的",z:["ㄩㄥˇ","ㄍㄢˇ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 14"] },
  "remind": { s:[{zh:"提醒",z:["ㄊㄧˊ","ㄒㄧㄥˇ"]}], src:["CET Vocabulary / Wk 14"] },
  "talented": { s:[{zh:"有天賦的",z:["ㄧㄡˇ","ㄊㄧㄢ","ㄈㄨˋ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 14"] },
  "wait": { s:[{zh:"等待",z:["ㄉㄥˇ","ㄉㄞˋ"]}], src:["CET Vocabulary / Wk 14"] },
  "minute": { s:[{zh:"分鐘",z:["ㄈㄣ","ㄓㄨㄥ"]}], src:["CET Vocabulary / Wk 14"] },
  "job": { s:[{zh:"工作",z:["ㄍㄨㄥ","ㄗㄨㄛˋ"]}], src:["CET Vocabulary / Wk 14"] },
  "trick": { s:[{zh:"把戲",z:["ㄅㄚˇ","ㄒㄧˋ"]}], src:["CET Vocabulary / Wk 15&16"] },
  "flew": { s:[{zh:"飛",z:["ㄈㄟ"],note:"過去式"}], src:["CET Vocabulary / Wk 15&16"] },
  "start": { s:[{zh:"開始",z:["ㄎㄞ","ㄕˇ"]}], src:["CET Vocabulary / Wk 15&16"] },
  "famous": { s:[{zh:"有名的",z:["ㄧㄡˇ","ㄇㄧㄥˊ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 15&16"] },
  "stop": { s:[{zh:"停止",z:["ㄊㄧㄥˊ","ㄓˇ"]}], src:["CET Vocabulary / Wk 15&16"] },
  "elf": { s:[{zh:"精靈",z:["ㄐㄧㄥ","ㄌㄧㄥˊ"]}], src:["CET Vocabulary / Wk 18"] },
  "shoemaker": { s:[{zh:"鞋匠",z:["ㄒㄧㄝˊ","ㄐㄧㄤˋ"]}], src:["CET Vocabulary / Wk 18"] },
  "leather": { s:[{zh:"皮革",z:["ㄆㄧˊ","ㄍㄜˊ"]}], src:["CET Vocabulary / Wk 18"] },
  "shed": { s:[{zh:"小屋",z:["ㄒㄧㄠˇ","ㄨ"]}], src:["CET Vocabulary / Wk 18"] },
  "pair": { s:[{zh:"一對",z:["ㄧˊ","ㄉㄨㄟˋ"]}], src:["CET Vocabulary / Wk 18"] },
  "shiny": { s:[{zh:"閃亮的",z:["ㄕㄢˇ","ㄌㄧㄤˋ","ㄉㄜ˙"]}], src:["CET Vocabulary / Wk 18"] },
  "peek": { s:[{zh:"偷看",z:["ㄊㄡ","ㄎㄢˋ"]}], src:["CET Vocabulary / Wk 18"] },
  "Monday": { s:[{zh:"星期一",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄧ"]}], src:["常用單字 / 星期"] },
  "Tuesday": { s:[{zh:"星期二",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄦˋ"]}], src:["常用單字 / 星期"] },
  "Wednesday": { s:[{zh:"星期三",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄙㄢ"]}], src:["常用單字 / 星期"] },
  "Thursday": { s:[{zh:"星期四",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄙˋ"]}], src:["常用單字 / 星期"] },
  "Friday": { s:[{zh:"星期五",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄨˇ"]}], src:["常用單字 / 星期"] },
  "Saturday": { s:[{zh:"星期六",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄌㄧㄡˋ"]}], src:["常用單字 / 星期"] },
  "Sunday": { s:[{zh:"星期日",z:["ㄒㄧㄥ","ㄑㄧˊ","ㄖˋ"]}], src:["常用單字 / 星期"] },
  "January": { s:[{zh:"一月",z:["ㄧ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "February": { s:[{zh:"二月",z:["ㄦˋ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "March": { s:[{zh:"三月",z:["ㄙㄢ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "April": { s:[{zh:"四月",z:["ㄙˋ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "May": { s:[{zh:"五月",z:["ㄨˇ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "June": { s:[{zh:"六月",z:["ㄌㄧㄡˋ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "July": { s:[{zh:"七月",z:["ㄑㄧ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "August": { s:[{zh:"八月",z:["ㄅㄚ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "September": { s:[{zh:"九月",z:["ㄐㄧㄡˇ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "October": { s:[{zh:"十月",z:["ㄕˊ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "November": { s:[{zh:"十一月",z:["ㄕˊ","ㄧ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] },
  "December": { s:[{zh:"十二月",z:["ㄕˊ","ㄦˋ","ㄩㄝˋ"]}], src:["常用單字 / 月份"] }
};

// ---- 向後相容層：組回舊的 "中文 (ㄅㄆㄇ)" 字串 ----
function formatSense(s) {
  const zy = s.z.filter(Boolean).join(" ");
  return s.zh + (zy ? " (" + zy + ")" : "") + (s.note ? "〔" + s.note + "〕" : "");
}

const wordTranslations = {};
for (const [w, e] of Object.entries(wordEntries)) {
  const text = e.s.map(formatSense).join(" / ");
  wordTranslations[w] = text;
  // 遊戲是用 wordTranslations[word.toLowerCase()] 查表，
  // 但 Monday~Sunday / January~December 這 19 個 key 是大寫開頭，
  // 原本永遠查不到中文。補上小寫別名。
  wordTranslations[w.toLowerCase()] = text;
}

// 給新程式用的查詢入口（不分大小寫）
function lookupWord(word) {
  const w = String(word).trim();
  return wordEntries[w] || wordEntries[w.toLowerCase()] ||
         Object.entries(wordEntries).find(([k]) => k.toLowerCase() === w.toLowerCase())?.[1] || null;
}
